// Mocks generated by Mockito 5.4.6 from annotations
// in winebar/test/prefix_creation_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:winebar/models/archive_type.dart' as _i12;
import 'package:winebar/models/wine_build.dart' as _i11;
import 'package:winebar/models/wine_build_source.dart' as _i7;
import 'package:winebar/models/wine_prefix.dart' as _i5;
import 'package:winebar/models/wine_release.dart' as _i10;
import 'package:winebar/repositories/wine_build_source_repo.dart' as _i6;
import 'package:winebar/services/wine_process_runner_service.dart' as _i3;
import 'package:winebar/utils/local_storage_paths.dart' as _i2;
import 'package:winebar/utils/startup_data.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLocalStoragePaths_0 extends _i1.SmartFake
    implements _i2.LocalStoragePaths {
  _FakeLocalStoragePaths_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWineProcessRunnerService_1 extends _i1.SmartFake
    implements _i3.WineProcessRunnerService {
  _FakeWineProcessRunnerService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StartupData].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartupData extends _i1.Mock implements _i4.StartupData {
  @override
  _i2.LocalStoragePaths get localStoragePaths =>
      (super.noSuchMethod(
            Invocation.getter(#localStoragePaths),
            returnValue: _FakeLocalStoragePaths_0(
              this,
              Invocation.getter(#localStoragePaths),
            ),
            returnValueForMissingStub: _FakeLocalStoragePaths_0(
              this,
              Invocation.getter(#localStoragePaths),
            ),
          )
          as _i2.LocalStoragePaths);

  @override
  List<_i5.WinePrefix> get winePrefixes =>
      (super.noSuchMethod(
            Invocation.getter(#winePrefixes),
            returnValue: <_i5.WinePrefix>[],
            returnValueForMissingStub: <_i5.WinePrefix>[],
          )
          as List<_i5.WinePrefix>);

  @override
  _i3.WineProcessRunnerService get wineProcessRunnerService =>
      (super.noSuchMethod(
            Invocation.getter(#wineProcessRunnerService),
            returnValue: _FakeWineProcessRunnerService_1(
              this,
              Invocation.getter(#wineProcessRunnerService),
            ),
            returnValueForMissingStub: _FakeWineProcessRunnerService_1(
              this,
              Invocation.getter(#wineProcessRunnerService),
            ),
          )
          as _i3.WineProcessRunnerService);

  @override
  bool get isNonIntelHost =>
      (super.noSuchMethod(
            Invocation.getter(#isNonIntelHost),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}

/// A class which mocks [WineBuildSourceRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockWineBuildSourceRepo extends _i1.Mock
    implements _i6.WineBuildSourceRepo {
  @override
  List<_i7.WineBuildSource> get sources =>
      (super.noSuchMethod(
            Invocation.getter(#sources),
            returnValue: <_i7.WineBuildSource>[],
            returnValueForMissingStub: <_i7.WineBuildSource>[],
          )
          as List<_i7.WineBuildSource>);
}

/// A class which mocks [WineBuildSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWineBuildSource extends _i1.Mock implements _i7.WineBuildSource {
  @override
  String get label =>
      (super.noSuchMethod(
            Invocation.getter(#label),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#label),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#label),
            ),
          )
          as String);

  @override
  String get directoryName =>
      (super.noSuchMethod(
            Invocation.getter(#directoryName),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#directoryName),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#directoryName),
            ),
          )
          as String);

  @override
  String get circleAvatarText =>
      (super.noSuchMethod(
            Invocation.getter(#circleAvatarText),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#circleAvatarText),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#circleAvatarText),
            ),
          )
          as String);

  @override
  _i9.Future<List<_i10.WineRelease>> getAvailableReleases({
    bool? refresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableReleases, [], {#refresh: refresh}),
            returnValue: _i9.Future<List<_i10.WineRelease>>.value(
              <_i10.WineRelease>[],
            ),
            returnValueForMissingStub: _i9.Future<List<_i10.WineRelease>>.value(
              <_i10.WineRelease>[],
            ),
          )
          as _i9.Future<List<_i10.WineRelease>>);
}

/// A class which mocks [WineRelease].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockWineRelease extends _i1.Mock implements _i10.WineRelease {
  @override
  String get releaseName =>
      (super.noSuchMethod(
            Invocation.getter(#releaseName),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#releaseName),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#releaseName),
            ),
          )
          as String);

  @override
  List<_i11.WineBuild> get builds =>
      (super.noSuchMethod(
            Invocation.getter(#builds),
            returnValue: <_i11.WineBuild>[],
            returnValueForMissingStub: <_i11.WineBuild>[],
          )
          as List<_i11.WineBuild>);

  @override
  List<Object> get props =>
      (super.noSuchMethod(
            Invocation.getter(#props),
            returnValue: <Object>[],
            returnValueForMissingStub: <Object>[],
          )
          as List<Object>);
}

/// A class which mocks [WineBuild].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockWineBuild extends _i1.Mock implements _i11.WineBuild {
  @override
  String get archiveFileName =>
      (super.noSuchMethod(
            Invocation.getter(#archiveFileName),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#archiveFileName),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#archiveFileName),
            ),
          )
          as String);

  @override
  _i12.ArchiveType get archiveType =>
      (super.noSuchMethod(
            Invocation.getter(#archiveType),
            returnValue: _i12.ArchiveType.tarGz,
            returnValueForMissingStub: _i12.ArchiveType.tarGz,
          )
          as _i12.ArchiveType);

  @override
  String get downloadUrl =>
      (super.noSuchMethod(
            Invocation.getter(#downloadUrl),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#downloadUrl),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#downloadUrl),
            ),
          )
          as String);

  @override
  List<Object> get props =>
      (super.noSuchMethod(
            Invocation.getter(#props),
            returnValue: <Object>[],
            returnValueForMissingStub: <Object>[],
          )
          as List<Object>);

  @override
  bool get isWow64Build =>
      (super.noSuchMethod(
            Invocation.getter(#isWow64Build),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}
