// Mocks generated by Mockito 5.4.6 from annotations
// in winebar/test/prefix_creation_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i15;

import 'package:flutter/material.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:winebar/models/archive_type.dart' as _i18;
import 'package:winebar/models/donation_solicitation_state.dart' as _i9;
import 'package:winebar/models/settings_json_file.dart' as _i2;
import 'package:winebar/models/suppressable_warning.dart' as _i8;
import 'package:winebar/models/wine_build.dart' as _i17;
import 'package:winebar/models/wine_build_source.dart' as _i12;
import 'package:winebar/models/wine_release.dart' as _i16;
import 'package:winebar/repositories/wine_build_source_repo.dart' as _i11;
import 'package:winebar/repositories/wine_locale_repo.dart' as _i5;
import 'package:winebar/repositories/wine_prefix_repo.dart' as _i4;
import 'package:winebar/services/app_settings_service.dart' as _i7;
import 'package:winebar/services/wine_process_runner_service.dart' as _i6;
import 'package:winebar/utils/local_storage_paths.dart' as _i3;
import 'package:winebar/utils/startup_data.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSettingsJsonFile_0 extends _i1.SmartFake
    implements _i2.SettingsJsonFile {
  _FakeSettingsJsonFile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocalStoragePaths_1 extends _i1.SmartFake
    implements _i3.LocalStoragePaths {
  _FakeLocalStoragePaths_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWinePrefixRepo_2 extends _i1.SmartFake
    implements _i4.WinePrefixRepo {
  _FakeWinePrefixRepo_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWineLocaleRepo_3 extends _i1.SmartFake
    implements _i5.WineLocaleRepo {
  _FakeWineLocaleRepo_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWineProcessRunnerService_4 extends _i1.SmartFake
    implements _i6.WineProcessRunnerService {
  _FakeWineProcessRunnerService_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppSettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppSettingsService extends _i1.Mock
    implements _i7.AppSettingsService {
  @override
  _i2.SettingsJsonFile get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeSettingsJsonFile_0(
              this,
              Invocation.getter(#settings),
            ),
            returnValueForMissingStub: _FakeSettingsJsonFile_0(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i2.SettingsJsonFile);

  @override
  void setWarningSuppressed(
    _i8.SuppressableWarning? warning, {
    required bool? suppressed,
  }) => super.noSuchMethod(
    Invocation.method(
      #setWarningSuppressed,
      [warning],
      {#suppressed: suppressed},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void setDonationSolicitationState(_i9.DonationSolicitationState? state) =>
      super.noSuchMethod(
        Invocation.method(#setDonationSolicitationState, [state]),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [StartupData].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartupData extends _i1.Mock implements _i10.StartupData {
  @override
  _i3.LocalStoragePaths get localStoragePaths =>
      (super.noSuchMethod(
            Invocation.getter(#localStoragePaths),
            returnValue: _FakeLocalStoragePaths_1(
              this,
              Invocation.getter(#localStoragePaths),
            ),
            returnValueForMissingStub: _FakeLocalStoragePaths_1(
              this,
              Invocation.getter(#localStoragePaths),
            ),
          )
          as _i3.LocalStoragePaths);

  @override
  _i4.WinePrefixRepo get winePrefixRepo =>
      (super.noSuchMethod(
            Invocation.getter(#winePrefixRepo),
            returnValue: _FakeWinePrefixRepo_2(
              this,
              Invocation.getter(#winePrefixRepo),
            ),
            returnValueForMissingStub: _FakeWinePrefixRepo_2(
              this,
              Invocation.getter(#winePrefixRepo),
            ),
          )
          as _i4.WinePrefixRepo);

  @override
  _i5.WineLocaleRepo get wineLocaleRepo =>
      (super.noSuchMethod(
            Invocation.getter(#wineLocaleRepo),
            returnValue: _FakeWineLocaleRepo_3(
              this,
              Invocation.getter(#wineLocaleRepo),
            ),
            returnValueForMissingStub: _FakeWineLocaleRepo_3(
              this,
              Invocation.getter(#wineLocaleRepo),
            ),
          )
          as _i5.WineLocaleRepo);

  @override
  _i6.WineProcessRunnerService get wineProcessRunnerService =>
      (super.noSuchMethod(
            Invocation.getter(#wineProcessRunnerService),
            returnValue: _FakeWineProcessRunnerService_4(
              this,
              Invocation.getter(#wineProcessRunnerService),
            ),
            returnValueForMissingStub: _FakeWineProcessRunnerService_4(
              this,
              Invocation.getter(#wineProcessRunnerService),
            ),
          )
          as _i6.WineProcessRunnerService);

  @override
  bool get isIntelHost =>
      (super.noSuchMethod(
            Invocation.getter(#isIntelHost),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get wineWillRunUnderMuvm =>
      (super.noSuchMethod(
            Invocation.getter(#wineWillRunUnderMuvm),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}

/// A class which mocks [WineBuildSourceRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockWineBuildSourceRepo extends _i1.Mock
    implements _i11.WineBuildSourceRepo {
  @override
  List<_i12.WineBuildSource> get sources =>
      (super.noSuchMethod(
            Invocation.getter(#sources),
            returnValue: <_i12.WineBuildSource>[],
            returnValueForMissingStub: <_i12.WineBuildSource>[],
          )
          as List<_i12.WineBuildSource>);
}

/// A class which mocks [WineBuildSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWineBuildSource extends _i1.Mock implements _i12.WineBuildSource {
  @override
  String get label =>
      (super.noSuchMethod(
            Invocation.getter(#label),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#label),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#label),
            ),
          )
          as String);

  @override
  bool get recommended =>
      (super.noSuchMethod(
            Invocation.getter(#recommended),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get directoryName =>
      (super.noSuchMethod(
            Invocation.getter(#directoryName),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#directoryName),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#directoryName),
            ),
          )
          as String);

  @override
  String get circleAvatarText =>
      (super.noSuchMethod(
            Invocation.getter(#circleAvatarText),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#circleAvatarText),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#circleAvatarText),
            ),
          )
          as String);

  @override
  bool get buildsMaySupportBothWin64AndWow64Modes =>
      (super.noSuchMethod(
            Invocation.getter(#buildsMaySupportBothWin64AndWow64Modes),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String? getDescription(_i14.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#getDescription, [context]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  _i15.Future<List<_i16.WineRelease>> getAvailableReleases({
    bool? refresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableReleases, [], {#refresh: refresh}),
            returnValue: _i15.Future<List<_i16.WineRelease>>.value(
              <_i16.WineRelease>[],
            ),
            returnValueForMissingStub:
                _i15.Future<List<_i16.WineRelease>>.value(<_i16.WineRelease>[]),
          )
          as _i15.Future<List<_i16.WineRelease>>);
}

/// A class which mocks [WineRelease].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockWineRelease extends _i1.Mock implements _i16.WineRelease {
  @override
  String get releaseName =>
      (super.noSuchMethod(
            Invocation.getter(#releaseName),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#releaseName),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#releaseName),
            ),
          )
          as String);

  @override
  List<_i17.WineBuild> get builds =>
      (super.noSuchMethod(
            Invocation.getter(#builds),
            returnValue: <_i17.WineBuild>[],
            returnValueForMissingStub: <_i17.WineBuild>[],
          )
          as List<_i17.WineBuild>);

  @override
  List<Object> get props =>
      (super.noSuchMethod(
            Invocation.getter(#props),
            returnValue: <Object>[],
            returnValueForMissingStub: <Object>[],
          )
          as List<Object>);
}

/// A class which mocks [WineBuild].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockWineBuild extends _i1.Mock implements _i17.WineBuild {
  @override
  String get archiveFileName =>
      (super.noSuchMethod(
            Invocation.getter(#archiveFileName),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#archiveFileName),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#archiveFileName),
            ),
          )
          as String);

  @override
  _i18.ArchiveType get archiveType =>
      (super.noSuchMethod(
            Invocation.getter(#archiveType),
            returnValue: _i18.ArchiveType.tarGz,
            returnValueForMissingStub: _i18.ArchiveType.tarGz,
          )
          as _i18.ArchiveType);

  @override
  String get downloadUrl =>
      (super.noSuchMethod(
            Invocation.getter(#downloadUrl),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#downloadUrl),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#downloadUrl),
            ),
          )
          as String);

  @override
  List<Object> get props =>
      (super.noSuchMethod(
            Invocation.getter(#props),
            returnValue: <Object>[],
            returnValueForMissingStub: <Object>[],
          )
          as List<Object>);

  @override
  bool get hasWow64InName =>
      (super.noSuchMethod(
            Invocation.getter(#hasWow64InName),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}
