// Mocks generated by Mockito 5.4.6 from annotations
// in winebar/test/prefix_cloning_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:bloc/bloc.dart' as _i6;
import 'package:flutter/src/widgets/navigator.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:winebar/blocs/prefix_cloning/prefix_cloning_bloc.dart' as _i3;
import 'package:winebar/blocs/prefix_cloning/prefix_cloning_state.dart' as _i2;
import 'package:winebar/models/wine_prefix.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePrefixCloningState_0 extends _i1.SmartFake
    implements _i2.PrefixCloningState {
  _FakePrefixCloningState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PrefixCloningBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrefixCloningBloc extends _i1.Mock implements _i3.PrefixCloningBloc {
  @override
  void Function(_i4.WinePrefix) get onPrefixCloned =>
      (super.noSuchMethod(
            Invocation.getter(#onPrefixCloned),
            returnValue: (_i4.WinePrefix newPrefix) {},
            returnValueForMissingStub: (_i4.WinePrefix newPrefix) {},
          )
          as void Function(_i4.WinePrefix));

  @override
  _i2.PrefixCloningState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakePrefixCloningState_0(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _FakePrefixCloningState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.PrefixCloningState);

  @override
  _i5.Stream<_i2.PrefixCloningState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i2.PrefixCloningState>.empty(),
            returnValueForMissingStub:
                _i5.Stream<_i2.PrefixCloningState>.empty(),
          )
          as _i5.Stream<_i2.PrefixCloningState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setTargetPrefixName(String? prefixName) => super.noSuchMethod(
    Invocation.method(#setTargetPrefixName, [prefixName]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> clonePrefixAndHandleErrors({
    required _i4.WinePrefix? prefixToClone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clonePrefixAndHandleErrors, [], {
              #prefixToClone: prefixToClone,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void emit(_i2.PrefixCloningState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i6.Change<_i2.PrefixCloningState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i7.NavigatorObserver {
  @override
  void didPush(_i7.Route<dynamic>? route, _i7.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPush, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didPop(_i7.Route<dynamic>? route, _i7.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPop, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i7.Route<dynamic>? route,
    _i7.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didRemove, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didReplace({
    _i7.Route<dynamic>? newRoute,
    _i7.Route<dynamic>? oldRoute,
  }) => super.noSuchMethod(
    Invocation.method(#didReplace, [], {
      #newRoute: newRoute,
      #oldRoute: oldRoute,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTop(
    _i7.Route<dynamic>? topRoute,
    _i7.Route<dynamic>? previousTopRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didChangeTop, [topRoute, previousTopRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStartUserGesture(
    _i7.Route<dynamic>? route,
    _i7.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didStartUserGesture, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStopUserGesture() => super.noSuchMethod(
    Invocation.method(#didStopUserGesture, []),
    returnValueForMissingStub: null,
  );
}
