// Mocks generated by Mockito 5.4.6 from annotations
// in winebar/test/prefix_cloning_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:convert' as _i17;
import 'dart:io' as _i6;
import 'dart:typed_data' as _i19;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:process/process.dart' as _i16;
import 'package:winebar/models/dxvk_build.dart' as _i14;
import 'package:winebar/models/wine_build.dart' as _i13;
import 'package:winebar/models/wine_build_source.dart' as _i11;
import 'package:winebar/models/wine_prefix.dart' as _i15;
import 'package:winebar/models/wine_prefix_dir_structure.dart' as _i7;
import 'package:winebar/models/wine_release.dart' as _i12;
import 'package:winebar/repositories/wine_locale_repo.dart' as _i4;
import 'package:winebar/repositories/wine_prefix_repo.dart' as _i3;
import 'package:winebar/services/wine_process_runner_service.dart' as _i5;
import 'package:winebar/utils/local_storage_paths.dart' as _i2;
import 'package:winebar/utils/startup_data.dart' as _i8;

import 'prefix_cloning_bloc_test.dart' as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLocalStoragePaths_0 extends _i1.SmartFake
    implements _i2.LocalStoragePaths {
  _FakeLocalStoragePaths_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWinePrefixRepo_1 extends _i1.SmartFake
    implements _i3.WinePrefixRepo {
  _FakeWinePrefixRepo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWineLocaleRepo_2 extends _i1.SmartFake
    implements _i4.WineLocaleRepo {
  _FakeWineLocaleRepo_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWineProcessRunnerService_3 extends _i1.SmartFake
    implements _i5.WineProcessRunnerService {
  _FakeWineProcessRunnerService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDirectory_4 extends _i1.SmartFake implements _i6.Directory {
  _FakeDirectory_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWinePrefixDirStructure_5 extends _i1.SmartFake
    implements _i7.WinePrefixDirStructure {
  _FakeWinePrefixDirStructure_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProcess_6 extends _i1.SmartFake implements _i6.Process {
  _FakeProcess_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_7 extends _i1.SmartFake implements _i6.File {
  _FakeFile_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_8 extends _i1.SmartFake implements Uri {
  _FakeUri_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileSystemEntity_9 extends _i1.SmartFake
    implements _i6.FileSystemEntity {
  _FakeFileSystemEntity_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileStat_10 extends _i1.SmartFake implements _i6.FileStat {
  _FakeFileStat_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_11 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRandomAccessFile_12 extends _i1.SmartFake
    implements _i6.RandomAccessFile {
  _FakeRandomAccessFile_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSink_13 extends _i1.SmartFake implements _i6.IOSink {
  _FakeIOSink_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StartupData].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartupData extends _i1.Mock implements _i8.StartupData {
  @override
  _i2.LocalStoragePaths get localStoragePaths =>
      (super.noSuchMethod(
            Invocation.getter(#localStoragePaths),
            returnValue: _FakeLocalStoragePaths_0(
              this,
              Invocation.getter(#localStoragePaths),
            ),
            returnValueForMissingStub: _FakeLocalStoragePaths_0(
              this,
              Invocation.getter(#localStoragePaths),
            ),
          )
          as _i2.LocalStoragePaths);

  @override
  _i3.WinePrefixRepo get winePrefixRepo =>
      (super.noSuchMethod(
            Invocation.getter(#winePrefixRepo),
            returnValue: _FakeWinePrefixRepo_1(
              this,
              Invocation.getter(#winePrefixRepo),
            ),
            returnValueForMissingStub: _FakeWinePrefixRepo_1(
              this,
              Invocation.getter(#winePrefixRepo),
            ),
          )
          as _i3.WinePrefixRepo);

  @override
  _i4.WineLocaleRepo get wineLocaleRepo =>
      (super.noSuchMethod(
            Invocation.getter(#wineLocaleRepo),
            returnValue: _FakeWineLocaleRepo_2(
              this,
              Invocation.getter(#wineLocaleRepo),
            ),
            returnValueForMissingStub: _FakeWineLocaleRepo_2(
              this,
              Invocation.getter(#wineLocaleRepo),
            ),
          )
          as _i4.WineLocaleRepo);

  @override
  _i5.WineProcessRunnerService get wineProcessRunnerService =>
      (super.noSuchMethod(
            Invocation.getter(#wineProcessRunnerService),
            returnValue: _FakeWineProcessRunnerService_3(
              this,
              Invocation.getter(#wineProcessRunnerService),
            ),
            returnValueForMissingStub: _FakeWineProcessRunnerService_3(
              this,
              Invocation.getter(#wineProcessRunnerService),
            ),
          )
          as _i5.WineProcessRunnerService);

  @override
  bool get isIntelHost =>
      (super.noSuchMethod(
            Invocation.getter(#isIntelHost),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get wineWillRunUnderMuvm =>
      (super.noSuchMethod(
            Invocation.getter(#wineWillRunUnderMuvm),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}

/// A class which mocks [LocalStoragePaths].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStoragePaths extends _i1.Mock implements _i2.LocalStoragePaths {
  @override
  String get homeDir =>
      (super.noSuchMethod(
            Invocation.getter(#homeDir),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#homeDir),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#homeDir),
            ),
          )
          as String);

  @override
  String get toplevelDataDir =>
      (super.noSuchMethod(
            Invocation.getter(#toplevelDataDir),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#toplevelDataDir),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#toplevelDataDir),
            ),
          )
          as String);

  @override
  String get settingsJsonFilePath =>
      (super.noSuchMethod(
            Invocation.getter(#settingsJsonFilePath),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#settingsJsonFilePath),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#settingsJsonFilePath),
            ),
          )
          as String);

  @override
  String get wineInstallsDir =>
      (super.noSuchMethod(
            Invocation.getter(#wineInstallsDir),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#wineInstallsDir),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#wineInstallsDir),
            ),
          )
          as String);

  @override
  String get winePrefixesDir =>
      (super.noSuchMethod(
            Invocation.getter(#winePrefixesDir),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#winePrefixesDir),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#winePrefixesDir),
            ),
          )
          as String);

  @override
  String get dxvkPackagesDir =>
      (super.noSuchMethod(
            Invocation.getter(#dxvkPackagesDir),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#dxvkPackagesDir),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#dxvkPackagesDir),
            ),
          )
          as String);

  @override
  String get tempDir =>
      (super.noSuchMethod(
            Invocation.getter(#tempDir),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#tempDir),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#tempDir),
            ),
          )
          as String);

  @override
  _i10.Future<_i6.Directory> createProcessOutputDir() =>
      (super.noSuchMethod(
            Invocation.method(#createProcessOutputDir, []),
            returnValue: _i10.Future<_i6.Directory>.value(
              _FakeDirectory_4(
                this,
                Invocation.method(#createProcessOutputDir, []),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i6.Directory>.value(
              _FakeDirectory_4(
                this,
                Invocation.method(#createProcessOutputDir, []),
              ),
            ),
          )
          as _i10.Future<_i6.Directory>);

  @override
  String getWineInstallDir({
    required _i11.WineBuildSource? wineBuildSource,
    required _i12.WineRelease? wineRelease,
    required _i13.WineBuild? wineBuild,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWineInstallDir, [], {
              #wineBuildSource: wineBuildSource,
              #wineRelease: wineRelease,
              #wineBuild: wineBuild,
            }),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#getWineInstallDir, [], {
                #wineBuildSource: wineBuildSource,
                #wineRelease: wineRelease,
                #wineBuild: wineBuild,
              }),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.method(#getWineInstallDir, [], {
                #wineBuildSource: wineBuildSource,
                #wineRelease: wineRelease,
                #wineBuild: wineBuild,
              }),
            ),
          )
          as String);

  @override
  String getDxvkPackageDir({required _i14.DxvkBuild? dxvkBuild}) =>
      (super.noSuchMethod(
            Invocation.method(#getDxvkPackageDir, [], {#dxvkBuild: dxvkBuild}),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#getDxvkPackageDir, [], {
                #dxvkBuild: dxvkBuild,
              }),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.method(#getDxvkPackageDir, [], {
                #dxvkBuild: dxvkBuild,
              }),
            ),
          )
          as String);

  @override
  _i7.WinePrefixDirStructure getWinePrefixDirStructure({
    required String? prefixName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWinePrefixDirStructure, [], {
              #prefixName: prefixName,
            }),
            returnValue: _FakeWinePrefixDirStructure_5(
              this,
              Invocation.method(#getWinePrefixDirStructure, [], {
                #prefixName: prefixName,
              }),
            ),
            returnValueForMissingStub: _FakeWinePrefixDirStructure_5(
              this,
              Invocation.method(#getWinePrefixDirStructure, [], {
                #prefixName: prefixName,
              }),
            ),
          )
          as _i7.WinePrefixDirStructure);
}

/// A class which mocks [WinePrefixRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockWinePrefixRepo extends _i1.Mock implements _i3.WinePrefixRepo {
  @override
  List<_i15.WinePrefix> get orderedPrefixes =>
      (super.noSuchMethod(
            Invocation.getter(#orderedPrefixes),
            returnValue: <_i15.WinePrefix>[],
            returnValueForMissingStub: <_i15.WinePrefix>[],
          )
          as List<_i15.WinePrefix>);

  @override
  _i10.Stream<_i3.WinePrefixRepoEvent> get eventStream =>
      (super.noSuchMethod(
            Invocation.getter(#eventStream),
            returnValue: _i10.Stream<_i3.WinePrefixRepoEvent>.empty(),
            returnValueForMissingStub:
                _i10.Stream<_i3.WinePrefixRepoEvent>.empty(),
          )
          as _i10.Stream<_i3.WinePrefixRepoEvent>);

  @override
  void addPrefix(_i15.WinePrefix? newPrefix) => super.noSuchMethod(
    Invocation.method(#addPrefix, [newPrefix]),
    returnValueForMissingStub: null,
  );

  @override
  void removePrefix(_i15.WinePrefix? prefixToRemove) => super.noSuchMethod(
    Invocation.method(#removePrefix, [prefixToRemove]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ProcessManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockProcessManager extends _i1.Mock implements _i16.ProcessManager {
  @override
  _i10.Future<_i6.Process> start(
    List<Object>? command, {
    String? workingDirectory,
    Map<String, String>? environment,
    bool? includeParentEnvironment = true,
    bool? runInShell = false,
    _i6.ProcessStartMode? mode = _i6.ProcessStartMode.normal,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #start,
              [command],
              {
                #workingDirectory: workingDirectory,
                #environment: environment,
                #includeParentEnvironment: includeParentEnvironment,
                #runInShell: runInShell,
                #mode: mode,
              },
            ),
            returnValue: _i10.Future<_i6.Process>.value(
              _FakeProcess_6(
                this,
                Invocation.method(
                  #start,
                  [command],
                  {
                    #workingDirectory: workingDirectory,
                    #environment: environment,
                    #includeParentEnvironment: includeParentEnvironment,
                    #runInShell: runInShell,
                    #mode: mode,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i6.Process>.value(
              _FakeProcess_6(
                this,
                Invocation.method(
                  #start,
                  [command],
                  {
                    #workingDirectory: workingDirectory,
                    #environment: environment,
                    #includeParentEnvironment: includeParentEnvironment,
                    #runInShell: runInShell,
                    #mode: mode,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i6.Process>);

  @override
  _i10.Future<_i6.ProcessResult> run(
    List<Object>? command, {
    String? workingDirectory,
    Map<String, String>? environment,
    bool? includeParentEnvironment = true,
    bool? runInShell = false,
    _i17.Encoding? stdoutEncoding = const _i6.SystemEncoding(),
    _i17.Encoding? stderrEncoding = const _i6.SystemEncoding(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #run,
              [command],
              {
                #workingDirectory: workingDirectory,
                #environment: environment,
                #includeParentEnvironment: includeParentEnvironment,
                #runInShell: runInShell,
                #stdoutEncoding: stdoutEncoding,
                #stderrEncoding: stderrEncoding,
              },
            ),
            returnValue: _i10.Future<_i6.ProcessResult>.value(
              _i9.dummyValue<_i6.ProcessResult>(
                this,
                Invocation.method(
                  #run,
                  [command],
                  {
                    #workingDirectory: workingDirectory,
                    #environment: environment,
                    #includeParentEnvironment: includeParentEnvironment,
                    #runInShell: runInShell,
                    #stdoutEncoding: stdoutEncoding,
                    #stderrEncoding: stderrEncoding,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i6.ProcessResult>.value(
              _i9.dummyValue<_i6.ProcessResult>(
                this,
                Invocation.method(
                  #run,
                  [command],
                  {
                    #workingDirectory: workingDirectory,
                    #environment: environment,
                    #includeParentEnvironment: includeParentEnvironment,
                    #runInShell: runInShell,
                    #stdoutEncoding: stdoutEncoding,
                    #stderrEncoding: stderrEncoding,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i6.ProcessResult>);

  @override
  _i6.ProcessResult runSync(
    List<Object>? command, {
    String? workingDirectory,
    Map<String, String>? environment,
    bool? includeParentEnvironment = true,
    bool? runInShell = false,
    _i17.Encoding? stdoutEncoding = const _i6.SystemEncoding(),
    _i17.Encoding? stderrEncoding = const _i6.SystemEncoding(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runSync,
              [command],
              {
                #workingDirectory: workingDirectory,
                #environment: environment,
                #includeParentEnvironment: includeParentEnvironment,
                #runInShell: runInShell,
                #stdoutEncoding: stdoutEncoding,
                #stderrEncoding: stderrEncoding,
              },
            ),
            returnValue: _i9.dummyValue<_i6.ProcessResult>(
              this,
              Invocation.method(
                #runSync,
                [command],
                {
                  #workingDirectory: workingDirectory,
                  #environment: environment,
                  #includeParentEnvironment: includeParentEnvironment,
                  #runInShell: runInShell,
                  #stdoutEncoding: stdoutEncoding,
                  #stderrEncoding: stderrEncoding,
                },
              ),
            ),
            returnValueForMissingStub: _i9.dummyValue<_i6.ProcessResult>(
              this,
              Invocation.method(
                #runSync,
                [command],
                {
                  #workingDirectory: workingDirectory,
                  #environment: environment,
                  #includeParentEnvironment: includeParentEnvironment,
                  #runInShell: runInShell,
                  #stdoutEncoding: stdoutEncoding,
                  #stderrEncoding: stderrEncoding,
                },
              ),
            ),
          )
          as _i6.ProcessResult);

  @override
  bool canRun(dynamic executable, {String? workingDirectory}) =>
      (super.noSuchMethod(
            Invocation.method(
              #canRun,
              [executable],
              {#workingDirectory: workingDirectory},
            ),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool killPid(
    int? pid, [
    _i6.ProcessSignal? signal = _i6.ProcessSignal.sigterm,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#killPid, [pid, signal]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}

/// A class which mocks [IoOps].
///
/// See the documentation for Mockito's code generation for more information.
class MockIoOps extends _i1.Mock implements _i18.IoOps {
  @override
  _i6.Directory createDirectory(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#createDirectory, [path]),
            returnValue: _FakeDirectory_4(
              this,
              Invocation.method(#createDirectory, [path]),
            ),
            returnValueForMissingStub: _FakeDirectory_4(
              this,
              Invocation.method(#createDirectory, [path]),
            ),
          )
          as _i6.Directory);

  @override
  _i6.File createFile(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#createFile, [path]),
            returnValue: _FakeFile_7(
              this,
              Invocation.method(#createFile, [path]),
            ),
            returnValueForMissingStub: _FakeFile_7(
              this,
              Invocation.method(#createFile, [path]),
            ),
          )
          as _i6.File);
}

/// A class which mocks [Directory].
///
/// See the documentation for Mockito's code generation for more information.
class MockDirectory extends _i1.Mock implements _i6.Directory {
  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#path)),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
          )
          as String);

  @override
  Uri get uri =>
      (super.noSuchMethod(
            Invocation.getter(#uri),
            returnValue: _FakeUri_8(this, Invocation.getter(#uri)),
            returnValueForMissingStub: _FakeUri_8(
              this,
              Invocation.getter(#uri),
            ),
          )
          as Uri);

  @override
  _i6.Directory get absolute =>
      (super.noSuchMethod(
            Invocation.getter(#absolute),
            returnValue: _FakeDirectory_4(this, Invocation.getter(#absolute)),
            returnValueForMissingStub: _FakeDirectory_4(
              this,
              Invocation.getter(#absolute),
            ),
          )
          as _i6.Directory);

  @override
  bool get isAbsolute =>
      (super.noSuchMethod(
            Invocation.getter(#isAbsolute),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Directory get parent =>
      (super.noSuchMethod(
            Invocation.getter(#parent),
            returnValue: _FakeDirectory_4(this, Invocation.getter(#parent)),
            returnValueForMissingStub: _FakeDirectory_4(
              this,
              Invocation.getter(#parent),
            ),
          )
          as _i6.Directory);

  @override
  _i10.Future<_i6.Directory> create({bool? recursive = false}) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {#recursive: recursive}),
            returnValue: _i10.Future<_i6.Directory>.value(
              _FakeDirectory_4(
                this,
                Invocation.method(#create, [], {#recursive: recursive}),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i6.Directory>.value(
              _FakeDirectory_4(
                this,
                Invocation.method(#create, [], {#recursive: recursive}),
              ),
            ),
          )
          as _i10.Future<_i6.Directory>);

  @override
  void createSync({bool? recursive = false}) => super.noSuchMethod(
    Invocation.method(#createSync, [], {#recursive: recursive}),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<_i6.Directory> createTemp([String? prefix]) =>
      (super.noSuchMethod(
            Invocation.method(#createTemp, [prefix]),
            returnValue: _i10.Future<_i6.Directory>.value(
              _FakeDirectory_4(this, Invocation.method(#createTemp, [prefix])),
            ),
            returnValueForMissingStub: _i10.Future<_i6.Directory>.value(
              _FakeDirectory_4(this, Invocation.method(#createTemp, [prefix])),
            ),
          )
          as _i10.Future<_i6.Directory>);

  @override
  _i6.Directory createTempSync([String? prefix]) =>
      (super.noSuchMethod(
            Invocation.method(#createTempSync, [prefix]),
            returnValue: _FakeDirectory_4(
              this,
              Invocation.method(#createTempSync, [prefix]),
            ),
            returnValueForMissingStub: _FakeDirectory_4(
              this,
              Invocation.method(#createTempSync, [prefix]),
            ),
          )
          as _i6.Directory);

  @override
  _i10.Future<String> resolveSymbolicLinks() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSymbolicLinks, []),
            returnValue: _i10.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#resolveSymbolicLinks, []),
              ),
            ),
            returnValueForMissingStub: _i10.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#resolveSymbolicLinks, []),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  String resolveSymbolicLinksSync() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSymbolicLinksSync, []),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#resolveSymbolicLinksSync, []),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.method(#resolveSymbolicLinksSync, []),
            ),
          )
          as String);

  @override
  _i10.Future<_i6.Directory> rename(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#rename, [newPath]),
            returnValue: _i10.Future<_i6.Directory>.value(
              _FakeDirectory_4(this, Invocation.method(#rename, [newPath])),
            ),
            returnValueForMissingStub: _i10.Future<_i6.Directory>.value(
              _FakeDirectory_4(this, Invocation.method(#rename, [newPath])),
            ),
          )
          as _i10.Future<_i6.Directory>);

  @override
  _i6.Directory renameSync(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#renameSync, [newPath]),
            returnValue: _FakeDirectory_4(
              this,
              Invocation.method(#renameSync, [newPath]),
            ),
            returnValueForMissingStub: _FakeDirectory_4(
              this,
              Invocation.method(#renameSync, [newPath]),
            ),
          )
          as _i6.Directory);

  @override
  _i10.Future<_i6.FileSystemEntity> delete({bool? recursive = false}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {#recursive: recursive}),
            returnValue: _i10.Future<_i6.FileSystemEntity>.value(
              _FakeFileSystemEntity_9(
                this,
                Invocation.method(#delete, [], {#recursive: recursive}),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i6.FileSystemEntity>.value(
              _FakeFileSystemEntity_9(
                this,
                Invocation.method(#delete, [], {#recursive: recursive}),
              ),
            ),
          )
          as _i10.Future<_i6.FileSystemEntity>);

  @override
  void deleteSync({bool? recursive = false}) => super.noSuchMethod(
    Invocation.method(#deleteSync, [], {#recursive: recursive}),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Stream<_i6.FileSystemEntity> list({
    bool? recursive = false,
    bool? followLinks = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#list, [], {
              #recursive: recursive,
              #followLinks: followLinks,
            }),
            returnValue: _i10.Stream<_i6.FileSystemEntity>.empty(),
            returnValueForMissingStub:
                _i10.Stream<_i6.FileSystemEntity>.empty(),
          )
          as _i10.Stream<_i6.FileSystemEntity>);

  @override
  List<_i6.FileSystemEntity> listSync({
    bool? recursive = false,
    bool? followLinks = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listSync, [], {
              #recursive: recursive,
              #followLinks: followLinks,
            }),
            returnValue: <_i6.FileSystemEntity>[],
            returnValueForMissingStub: <_i6.FileSystemEntity>[],
          )
          as List<_i6.FileSystemEntity>);

  @override
  _i10.Future<bool> exists() =>
      (super.noSuchMethod(
            Invocation.method(#exists, []),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  bool existsSync() =>
      (super.noSuchMethod(
            Invocation.method(#existsSync, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i10.Future<_i6.FileStat> stat() =>
      (super.noSuchMethod(
            Invocation.method(#stat, []),
            returnValue: _i10.Future<_i6.FileStat>.value(
              _FakeFileStat_10(this, Invocation.method(#stat, [])),
            ),
            returnValueForMissingStub: _i10.Future<_i6.FileStat>.value(
              _FakeFileStat_10(this, Invocation.method(#stat, [])),
            ),
          )
          as _i10.Future<_i6.FileStat>);

  @override
  _i6.FileStat statSync() =>
      (super.noSuchMethod(
            Invocation.method(#statSync, []),
            returnValue: _FakeFileStat_10(
              this,
              Invocation.method(#statSync, []),
            ),
            returnValueForMissingStub: _FakeFileStat_10(
              this,
              Invocation.method(#statSync, []),
            ),
          )
          as _i6.FileStat);

  @override
  _i10.Stream<_i6.FileSystemEvent> watch({
    int? events = 15,
    bool? recursive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [], {
              #events: events,
              #recursive: recursive,
            }),
            returnValue: _i10.Stream<_i6.FileSystemEvent>.empty(),
            returnValueForMissingStub: _i10.Stream<_i6.FileSystemEvent>.empty(),
          )
          as _i10.Stream<_i6.FileSystemEvent>);
}

/// A class which mocks [File].
///
/// See the documentation for Mockito's code generation for more information.
class MockFile extends _i1.Mock implements _i6.File {
  @override
  _i6.File get absolute =>
      (super.noSuchMethod(
            Invocation.getter(#absolute),
            returnValue: _FakeFile_7(this, Invocation.getter(#absolute)),
            returnValueForMissingStub: _FakeFile_7(
              this,
              Invocation.getter(#absolute),
            ),
          )
          as _i6.File);

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#path)),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
          )
          as String);

  @override
  Uri get uri =>
      (super.noSuchMethod(
            Invocation.getter(#uri),
            returnValue: _FakeUri_8(this, Invocation.getter(#uri)),
            returnValueForMissingStub: _FakeUri_8(
              this,
              Invocation.getter(#uri),
            ),
          )
          as Uri);

  @override
  bool get isAbsolute =>
      (super.noSuchMethod(
            Invocation.getter(#isAbsolute),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Directory get parent =>
      (super.noSuchMethod(
            Invocation.getter(#parent),
            returnValue: _FakeDirectory_4(this, Invocation.getter(#parent)),
            returnValueForMissingStub: _FakeDirectory_4(
              this,
              Invocation.getter(#parent),
            ),
          )
          as _i6.Directory);

  @override
  _i10.Future<_i6.File> create({
    bool? recursive = false,
    bool? exclusive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #recursive: recursive,
              #exclusive: exclusive,
            }),
            returnValue: _i10.Future<_i6.File>.value(
              _FakeFile_7(
                this,
                Invocation.method(#create, [], {
                  #recursive: recursive,
                  #exclusive: exclusive,
                }),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i6.File>.value(
              _FakeFile_7(
                this,
                Invocation.method(#create, [], {
                  #recursive: recursive,
                  #exclusive: exclusive,
                }),
              ),
            ),
          )
          as _i10.Future<_i6.File>);

  @override
  void createSync({bool? recursive = false, bool? exclusive = false}) =>
      super.noSuchMethod(
        Invocation.method(#createSync, [], {
          #recursive: recursive,
          #exclusive: exclusive,
        }),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<_i6.File> rename(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#rename, [newPath]),
            returnValue: _i10.Future<_i6.File>.value(
              _FakeFile_7(this, Invocation.method(#rename, [newPath])),
            ),
            returnValueForMissingStub: _i10.Future<_i6.File>.value(
              _FakeFile_7(this, Invocation.method(#rename, [newPath])),
            ),
          )
          as _i10.Future<_i6.File>);

  @override
  _i6.File renameSync(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#renameSync, [newPath]),
            returnValue: _FakeFile_7(
              this,
              Invocation.method(#renameSync, [newPath]),
            ),
            returnValueForMissingStub: _FakeFile_7(
              this,
              Invocation.method(#renameSync, [newPath]),
            ),
          )
          as _i6.File);

  @override
  _i10.Future<_i6.FileSystemEntity> delete({bool? recursive = false}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {#recursive: recursive}),
            returnValue: _i10.Future<_i6.FileSystemEntity>.value(
              _FakeFileSystemEntity_9(
                this,
                Invocation.method(#delete, [], {#recursive: recursive}),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i6.FileSystemEntity>.value(
              _FakeFileSystemEntity_9(
                this,
                Invocation.method(#delete, [], {#recursive: recursive}),
              ),
            ),
          )
          as _i10.Future<_i6.FileSystemEntity>);

  @override
  void deleteSync({bool? recursive = false}) => super.noSuchMethod(
    Invocation.method(#deleteSync, [], {#recursive: recursive}),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<_i6.File> copy(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#copy, [newPath]),
            returnValue: _i10.Future<_i6.File>.value(
              _FakeFile_7(this, Invocation.method(#copy, [newPath])),
            ),
            returnValueForMissingStub: _i10.Future<_i6.File>.value(
              _FakeFile_7(this, Invocation.method(#copy, [newPath])),
            ),
          )
          as _i10.Future<_i6.File>);

  @override
  _i6.File copySync(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#copySync, [newPath]),
            returnValue: _FakeFile_7(
              this,
              Invocation.method(#copySync, [newPath]),
            ),
            returnValueForMissingStub: _FakeFile_7(
              this,
              Invocation.method(#copySync, [newPath]),
            ),
          )
          as _i6.File);

  @override
  _i10.Future<int> length() =>
      (super.noSuchMethod(
            Invocation.method(#length, []),
            returnValue: _i10.Future<int>.value(0),
            returnValueForMissingStub: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  int lengthSync() =>
      (super.noSuchMethod(
            Invocation.method(#lengthSync, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i10.Future<DateTime> lastAccessed() =>
      (super.noSuchMethod(
            Invocation.method(#lastAccessed, []),
            returnValue: _i10.Future<DateTime>.value(
              _FakeDateTime_11(this, Invocation.method(#lastAccessed, [])),
            ),
            returnValueForMissingStub: _i10.Future<DateTime>.value(
              _FakeDateTime_11(this, Invocation.method(#lastAccessed, [])),
            ),
          )
          as _i10.Future<DateTime>);

  @override
  DateTime lastAccessedSync() =>
      (super.noSuchMethod(
            Invocation.method(#lastAccessedSync, []),
            returnValue: _FakeDateTime_11(
              this,
              Invocation.method(#lastAccessedSync, []),
            ),
            returnValueForMissingStub: _FakeDateTime_11(
              this,
              Invocation.method(#lastAccessedSync, []),
            ),
          )
          as DateTime);

  @override
  _i10.Future<dynamic> setLastAccessed(DateTime? time) =>
      (super.noSuchMethod(
            Invocation.method(#setLastAccessed, [time]),
            returnValue: _i10.Future<dynamic>.value(),
            returnValueForMissingStub: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  void setLastAccessedSync(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setLastAccessedSync, [time]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<DateTime> lastModified() =>
      (super.noSuchMethod(
            Invocation.method(#lastModified, []),
            returnValue: _i10.Future<DateTime>.value(
              _FakeDateTime_11(this, Invocation.method(#lastModified, [])),
            ),
            returnValueForMissingStub: _i10.Future<DateTime>.value(
              _FakeDateTime_11(this, Invocation.method(#lastModified, [])),
            ),
          )
          as _i10.Future<DateTime>);

  @override
  DateTime lastModifiedSync() =>
      (super.noSuchMethod(
            Invocation.method(#lastModifiedSync, []),
            returnValue: _FakeDateTime_11(
              this,
              Invocation.method(#lastModifiedSync, []),
            ),
            returnValueForMissingStub: _FakeDateTime_11(
              this,
              Invocation.method(#lastModifiedSync, []),
            ),
          )
          as DateTime);

  @override
  _i10.Future<dynamic> setLastModified(DateTime? time) =>
      (super.noSuchMethod(
            Invocation.method(#setLastModified, [time]),
            returnValue: _i10.Future<dynamic>.value(),
            returnValueForMissingStub: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  void setLastModifiedSync(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setLastModifiedSync, [time]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<_i6.RandomAccessFile> open({
    _i6.FileMode? mode = _i6.FileMode.read,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#open, [], {#mode: mode}),
            returnValue: _i10.Future<_i6.RandomAccessFile>.value(
              _FakeRandomAccessFile_12(
                this,
                Invocation.method(#open, [], {#mode: mode}),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i6.RandomAccessFile>.value(
              _FakeRandomAccessFile_12(
                this,
                Invocation.method(#open, [], {#mode: mode}),
              ),
            ),
          )
          as _i10.Future<_i6.RandomAccessFile>);

  @override
  _i6.RandomAccessFile openSync({_i6.FileMode? mode = _i6.FileMode.read}) =>
      (super.noSuchMethod(
            Invocation.method(#openSync, [], {#mode: mode}),
            returnValue: _FakeRandomAccessFile_12(
              this,
              Invocation.method(#openSync, [], {#mode: mode}),
            ),
            returnValueForMissingStub: _FakeRandomAccessFile_12(
              this,
              Invocation.method(#openSync, [], {#mode: mode}),
            ),
          )
          as _i6.RandomAccessFile);

  @override
  _i10.Stream<List<int>> openRead([int? start, int? end]) =>
      (super.noSuchMethod(
            Invocation.method(#openRead, [start, end]),
            returnValue: _i10.Stream<List<int>>.empty(),
            returnValueForMissingStub: _i10.Stream<List<int>>.empty(),
          )
          as _i10.Stream<List<int>>);

  @override
  _i6.IOSink openWrite({
    _i6.FileMode? mode = _i6.FileMode.write,
    _i17.Encoding? encoding = const _i17.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#openWrite, [], {
              #mode: mode,
              #encoding: encoding,
            }),
            returnValue: _FakeIOSink_13(
              this,
              Invocation.method(#openWrite, [], {
                #mode: mode,
                #encoding: encoding,
              }),
            ),
            returnValueForMissingStub: _FakeIOSink_13(
              this,
              Invocation.method(#openWrite, [], {
                #mode: mode,
                #encoding: encoding,
              }),
            ),
          )
          as _i6.IOSink);

  @override
  _i10.Future<_i19.Uint8List> readAsBytes() =>
      (super.noSuchMethod(
            Invocation.method(#readAsBytes, []),
            returnValue: _i10.Future<_i19.Uint8List>.value(_i19.Uint8List(0)),
            returnValueForMissingStub: _i10.Future<_i19.Uint8List>.value(
              _i19.Uint8List(0),
            ),
          )
          as _i10.Future<_i19.Uint8List>);

  @override
  _i19.Uint8List readAsBytesSync() =>
      (super.noSuchMethod(
            Invocation.method(#readAsBytesSync, []),
            returnValue: _i19.Uint8List(0),
            returnValueForMissingStub: _i19.Uint8List(0),
          )
          as _i19.Uint8List);

  @override
  _i10.Future<String> readAsString({
    _i17.Encoding? encoding = const _i17.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsString, [], {#encoding: encoding}),
            returnValue: _i10.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [], {#encoding: encoding}),
              ),
            ),
            returnValueForMissingStub: _i10.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [], {#encoding: encoding}),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  String readAsStringSync({_i17.Encoding? encoding = const _i17.Utf8Codec()}) =>
      (super.noSuchMethod(
            Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
            ),
          )
          as String);

  @override
  _i10.Future<List<String>> readAsLines({
    _i17.Encoding? encoding = const _i17.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsLines, [], {#encoding: encoding}),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i10.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i10.Future<List<String>>);

  @override
  List<String> readAsLinesSync({
    _i17.Encoding? encoding = const _i17.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsLinesSync, [], {#encoding: encoding}),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  _i10.Future<_i6.File> writeAsBytes(
    List<int>? bytes, {
    _i6.FileMode? mode = _i6.FileMode.write,
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeAsBytes,
              [bytes],
              {#mode: mode, #flush: flush},
            ),
            returnValue: _i10.Future<_i6.File>.value(
              _FakeFile_7(
                this,
                Invocation.method(
                  #writeAsBytes,
                  [bytes],
                  {#mode: mode, #flush: flush},
                ),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i6.File>.value(
              _FakeFile_7(
                this,
                Invocation.method(
                  #writeAsBytes,
                  [bytes],
                  {#mode: mode, #flush: flush},
                ),
              ),
            ),
          )
          as _i10.Future<_i6.File>);

  @override
  void writeAsBytesSync(
    List<int>? bytes, {
    _i6.FileMode? mode = _i6.FileMode.write,
    bool? flush = false,
  }) => super.noSuchMethod(
    Invocation.method(#writeAsBytesSync, [bytes], {#mode: mode, #flush: flush}),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<_i6.File> writeAsString(
    String? contents, {
    _i6.FileMode? mode = _i6.FileMode.write,
    _i17.Encoding? encoding = const _i17.Utf8Codec(),
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeAsString,
              [contents],
              {#mode: mode, #encoding: encoding, #flush: flush},
            ),
            returnValue: _i10.Future<_i6.File>.value(
              _FakeFile_7(
                this,
                Invocation.method(
                  #writeAsString,
                  [contents],
                  {#mode: mode, #encoding: encoding, #flush: flush},
                ),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i6.File>.value(
              _FakeFile_7(
                this,
                Invocation.method(
                  #writeAsString,
                  [contents],
                  {#mode: mode, #encoding: encoding, #flush: flush},
                ),
              ),
            ),
          )
          as _i10.Future<_i6.File>);

  @override
  void writeAsStringSync(
    String? contents, {
    _i6.FileMode? mode = _i6.FileMode.write,
    _i17.Encoding? encoding = const _i17.Utf8Codec(),
    bool? flush = false,
  }) => super.noSuchMethod(
    Invocation.method(
      #writeAsStringSync,
      [contents],
      {#mode: mode, #encoding: encoding, #flush: flush},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<bool> exists() =>
      (super.noSuchMethod(
            Invocation.method(#exists, []),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  bool existsSync() =>
      (super.noSuchMethod(
            Invocation.method(#existsSync, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i10.Future<String> resolveSymbolicLinks() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSymbolicLinks, []),
            returnValue: _i10.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#resolveSymbolicLinks, []),
              ),
            ),
            returnValueForMissingStub: _i10.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#resolveSymbolicLinks, []),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  String resolveSymbolicLinksSync() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSymbolicLinksSync, []),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#resolveSymbolicLinksSync, []),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.method(#resolveSymbolicLinksSync, []),
            ),
          )
          as String);

  @override
  _i10.Future<_i6.FileStat> stat() =>
      (super.noSuchMethod(
            Invocation.method(#stat, []),
            returnValue: _i10.Future<_i6.FileStat>.value(
              _FakeFileStat_10(this, Invocation.method(#stat, [])),
            ),
            returnValueForMissingStub: _i10.Future<_i6.FileStat>.value(
              _FakeFileStat_10(this, Invocation.method(#stat, [])),
            ),
          )
          as _i10.Future<_i6.FileStat>);

  @override
  _i6.FileStat statSync() =>
      (super.noSuchMethod(
            Invocation.method(#statSync, []),
            returnValue: _FakeFileStat_10(
              this,
              Invocation.method(#statSync, []),
            ),
            returnValueForMissingStub: _FakeFileStat_10(
              this,
              Invocation.method(#statSync, []),
            ),
          )
          as _i6.FileStat);

  @override
  _i10.Stream<_i6.FileSystemEvent> watch({
    int? events = 15,
    bool? recursive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [], {
              #events: events,
              #recursive: recursive,
            }),
            returnValue: _i10.Stream<_i6.FileSystemEvent>.empty(),
            returnValueForMissingStub: _i10.Stream<_i6.FileSystemEvent>.empty(),
          )
          as _i10.Stream<_i6.FileSystemEvent>);
}
