// Mocks generated by Mockito 5.4.6 from annotations
// in winebar/test/prefix_settings_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:convert' as _i16;
import 'dart:io' as _i6;
import 'dart:typed_data' as _i17;
import 'dart:ui' as _i19;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:winebar/models/wine_build.dart' as _i15;
import 'package:winebar/models/wine_build_source.dart' as _i13;
import 'package:winebar/models/wine_prefix.dart' as _i8;
import 'package:winebar/models/wine_prefix_dir_structure.dart' as _i5;
import 'package:winebar/models/wine_release.dart' as _i14;
import 'package:winebar/repositories/running_executables_repo.dart' as _i18;
import 'package:winebar/services/utility_service.dart' as _i9;
import 'package:winebar/services/wine_process_runner_service.dart' as _i4;
import 'package:winebar/utils/local_storage_paths.dart' as _i3;
import 'package:winebar/utils/startup_data.dart' as _i11;
import 'package:winebar/utils/wine_installation_descriptor.dart' as _i2;

import 'prefix_settings_dialog_test.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWineInstallationDescriptor_0 extends _i1.SmartFake
    implements _i2.WineInstallationDescriptor {
  _FakeWineInstallationDescriptor_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocalStoragePaths_1 extends _i1.SmartFake
    implements _i3.LocalStoragePaths {
  _FakeLocalStoragePaths_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWineProcessRunnerService_2 extends _i1.SmartFake
    implements _i4.WineProcessRunnerService {
  _FakeWineProcessRunnerService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWinePrefixDirStructure_3 extends _i1.SmartFake
    implements _i5.WinePrefixDirStructure {
  _FakeWinePrefixDirStructure_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_4 extends _i1.SmartFake implements _i6.File {
  _FakeFile_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_5 extends _i1.SmartFake implements Uri {
  _FakeUri_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDirectory_6 extends _i1.SmartFake implements _i6.Directory {
  _FakeDirectory_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileSystemEntity_7 extends _i1.SmartFake
    implements _i6.FileSystemEntity {
  _FakeFileSystemEntity_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_8 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRandomAccessFile_9 extends _i1.SmartFake
    implements _i6.RandomAccessFile {
  _FakeRandomAccessFile_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSink_10 extends _i1.SmartFake implements _i6.IOSink {
  _FakeIOSink_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileStat_11 extends _i1.SmartFake implements _i6.FileStat {
  _FakeFileStat_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWineProcess_12 extends _i1.SmartFake implements _i4.WineProcess {
  _FakeWineProcess_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWineProcessResult_13 extends _i1.SmartFake
    implements _i4.WineProcessResult {
  _FakeWineProcessResult_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UpdatedPrefixReceiver].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdatedPrefixReceiver extends _i1.Mock
    implements _i7.UpdatedPrefixReceiver {
  @override
  void handleUpdatedPrefix(_i8.WinePrefix? updatedPrefix) => super.noSuchMethod(
    Invocation.method(#handleUpdatedPrefix, [updatedPrefix]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UtilityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUtilityService extends _i1.Mock implements _i9.UtilityService {
  @override
  _i10.Future<_i2.WineInstallationDescriptor>
  wineInstallationDescriptorForWineInstallDir(String? wineInstallDir) =>
      (super.noSuchMethod(
            Invocation.method(#wineInstallationDescriptorForWineInstallDir, [
              wineInstallDir,
            ]),
            returnValue: _i10.Future<_i2.WineInstallationDescriptor>.value(
              _FakeWineInstallationDescriptor_0(
                this,
                Invocation.method(
                  #wineInstallationDescriptorForWineInstallDir,
                  [wineInstallDir],
                ),
              ),
            ),
            returnValueForMissingStub:
                _i10.Future<_i2.WineInstallationDescriptor>.value(
                  _FakeWineInstallationDescriptor_0(
                    this,
                    Invocation.method(
                      #wineInstallationDescriptorForWineInstallDir,
                      [wineInstallDir],
                    ),
                  ),
                ),
          )
          as _i10.Future<_i2.WineInstallationDescriptor>);
}

/// A class which mocks [StartupData].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartupData extends _i1.Mock implements _i11.StartupData {
  @override
  _i3.LocalStoragePaths get localStoragePaths =>
      (super.noSuchMethod(
            Invocation.getter(#localStoragePaths),
            returnValue: _FakeLocalStoragePaths_1(
              this,
              Invocation.getter(#localStoragePaths),
            ),
            returnValueForMissingStub: _FakeLocalStoragePaths_1(
              this,
              Invocation.getter(#localStoragePaths),
            ),
          )
          as _i3.LocalStoragePaths);

  @override
  List<_i8.WinePrefix> get winePrefixes =>
      (super.noSuchMethod(
            Invocation.getter(#winePrefixes),
            returnValue: <_i8.WinePrefix>[],
            returnValueForMissingStub: <_i8.WinePrefix>[],
          )
          as List<_i8.WinePrefix>);

  @override
  _i4.WineProcessRunnerService get wineProcessRunnerService =>
      (super.noSuchMethod(
            Invocation.getter(#wineProcessRunnerService),
            returnValue: _FakeWineProcessRunnerService_2(
              this,
              Invocation.getter(#wineProcessRunnerService),
            ),
            returnValueForMissingStub: _FakeWineProcessRunnerService_2(
              this,
              Invocation.getter(#wineProcessRunnerService),
            ),
          )
          as _i4.WineProcessRunnerService);

  @override
  bool get isNonIntelHost =>
      (super.noSuchMethod(
            Invocation.getter(#isNonIntelHost),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get wineWillRunUnderMuvm =>
      (super.noSuchMethod(
            Invocation.getter(#wineWillRunUnderMuvm),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}

/// A class which mocks [LocalStoragePaths].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStoragePaths extends _i1.Mock implements _i3.LocalStoragePaths {
  @override
  String get homeDir =>
      (super.noSuchMethod(
            Invocation.getter(#homeDir),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#homeDir),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#homeDir),
            ),
          )
          as String);

  @override
  String get toplevelDataDir =>
      (super.noSuchMethod(
            Invocation.getter(#toplevelDataDir),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#toplevelDataDir),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#toplevelDataDir),
            ),
          )
          as String);

  @override
  String get settingsJsonFilePath =>
      (super.noSuchMethod(
            Invocation.getter(#settingsJsonFilePath),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#settingsJsonFilePath),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#settingsJsonFilePath),
            ),
          )
          as String);

  @override
  String get wineInstallsDir =>
      (super.noSuchMethod(
            Invocation.getter(#wineInstallsDir),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#wineInstallsDir),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#wineInstallsDir),
            ),
          )
          as String);

  @override
  String get winePrefixesDir =>
      (super.noSuchMethod(
            Invocation.getter(#winePrefixesDir),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#winePrefixesDir),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#winePrefixesDir),
            ),
          )
          as String);

  @override
  String get tempDir =>
      (super.noSuchMethod(
            Invocation.getter(#tempDir),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#tempDir),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#tempDir),
            ),
          )
          as String);

  @override
  String getWineInstallDir({
    required _i13.WineBuildSource? wineBuildSource,
    required _i14.WineRelease? wineRelease,
    required _i15.WineBuild? wineBuild,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWineInstallDir, [], {
              #wineBuildSource: wineBuildSource,
              #wineRelease: wineRelease,
              #wineBuild: wineBuild,
            }),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#getWineInstallDir, [], {
                #wineBuildSource: wineBuildSource,
                #wineRelease: wineRelease,
                #wineBuild: wineBuild,
              }),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.method(#getWineInstallDir, [], {
                #wineBuildSource: wineBuildSource,
                #wineRelease: wineRelease,
                #wineBuild: wineBuild,
              }),
            ),
          )
          as String);

  @override
  _i5.WinePrefixDirStructure getWinePrefixDirStructure({
    required String? prefixName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWinePrefixDirStructure, [], {
              #prefixName: prefixName,
            }),
            returnValue: _FakeWinePrefixDirStructure_3(
              this,
              Invocation.method(#getWinePrefixDirStructure, [], {
                #prefixName: prefixName,
              }),
            ),
            returnValueForMissingStub: _FakeWinePrefixDirStructure_3(
              this,
              Invocation.method(#getWinePrefixDirStructure, [], {
                #prefixName: prefixName,
              }),
            ),
          )
          as _i5.WinePrefixDirStructure);
}

/// A class which mocks [IoOps].
///
/// See the documentation for Mockito's code generation for more information.
class MockIoOps extends _i1.Mock implements _i7.IoOps {
  @override
  _i6.File createFile(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#createFile, [path]),
            returnValue: _FakeFile_4(
              this,
              Invocation.method(#createFile, [path]),
            ),
            returnValueForMissingStub: _FakeFile_4(
              this,
              Invocation.method(#createFile, [path]),
            ),
          )
          as _i6.File);
}

/// A class which mocks [File].
///
/// See the documentation for Mockito's code generation for more information.
class MockFile extends _i1.Mock implements _i6.File {
  @override
  _i6.File get absolute =>
      (super.noSuchMethod(
            Invocation.getter(#absolute),
            returnValue: _FakeFile_4(this, Invocation.getter(#absolute)),
            returnValueForMissingStub: _FakeFile_4(
              this,
              Invocation.getter(#absolute),
            ),
          )
          as _i6.File);

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
          )
          as String);

  @override
  Uri get uri =>
      (super.noSuchMethod(
            Invocation.getter(#uri),
            returnValue: _FakeUri_5(this, Invocation.getter(#uri)),
            returnValueForMissingStub: _FakeUri_5(
              this,
              Invocation.getter(#uri),
            ),
          )
          as Uri);

  @override
  bool get isAbsolute =>
      (super.noSuchMethod(
            Invocation.getter(#isAbsolute),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Directory get parent =>
      (super.noSuchMethod(
            Invocation.getter(#parent),
            returnValue: _FakeDirectory_6(this, Invocation.getter(#parent)),
            returnValueForMissingStub: _FakeDirectory_6(
              this,
              Invocation.getter(#parent),
            ),
          )
          as _i6.Directory);

  @override
  _i10.Future<_i6.File> create({
    bool? recursive = false,
    bool? exclusive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #recursive: recursive,
              #exclusive: exclusive,
            }),
            returnValue: _i10.Future<_i6.File>.value(
              _FakeFile_4(
                this,
                Invocation.method(#create, [], {
                  #recursive: recursive,
                  #exclusive: exclusive,
                }),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i6.File>.value(
              _FakeFile_4(
                this,
                Invocation.method(#create, [], {
                  #recursive: recursive,
                  #exclusive: exclusive,
                }),
              ),
            ),
          )
          as _i10.Future<_i6.File>);

  @override
  void createSync({bool? recursive = false, bool? exclusive = false}) =>
      super.noSuchMethod(
        Invocation.method(#createSync, [], {
          #recursive: recursive,
          #exclusive: exclusive,
        }),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<_i6.File> rename(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#rename, [newPath]),
            returnValue: _i10.Future<_i6.File>.value(
              _FakeFile_4(this, Invocation.method(#rename, [newPath])),
            ),
            returnValueForMissingStub: _i10.Future<_i6.File>.value(
              _FakeFile_4(this, Invocation.method(#rename, [newPath])),
            ),
          )
          as _i10.Future<_i6.File>);

  @override
  _i6.File renameSync(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#renameSync, [newPath]),
            returnValue: _FakeFile_4(
              this,
              Invocation.method(#renameSync, [newPath]),
            ),
            returnValueForMissingStub: _FakeFile_4(
              this,
              Invocation.method(#renameSync, [newPath]),
            ),
          )
          as _i6.File);

  @override
  _i10.Future<_i6.FileSystemEntity> delete({bool? recursive = false}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {#recursive: recursive}),
            returnValue: _i10.Future<_i6.FileSystemEntity>.value(
              _FakeFileSystemEntity_7(
                this,
                Invocation.method(#delete, [], {#recursive: recursive}),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i6.FileSystemEntity>.value(
              _FakeFileSystemEntity_7(
                this,
                Invocation.method(#delete, [], {#recursive: recursive}),
              ),
            ),
          )
          as _i10.Future<_i6.FileSystemEntity>);

  @override
  void deleteSync({bool? recursive = false}) => super.noSuchMethod(
    Invocation.method(#deleteSync, [], {#recursive: recursive}),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<_i6.File> copy(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#copy, [newPath]),
            returnValue: _i10.Future<_i6.File>.value(
              _FakeFile_4(this, Invocation.method(#copy, [newPath])),
            ),
            returnValueForMissingStub: _i10.Future<_i6.File>.value(
              _FakeFile_4(this, Invocation.method(#copy, [newPath])),
            ),
          )
          as _i10.Future<_i6.File>);

  @override
  _i6.File copySync(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#copySync, [newPath]),
            returnValue: _FakeFile_4(
              this,
              Invocation.method(#copySync, [newPath]),
            ),
            returnValueForMissingStub: _FakeFile_4(
              this,
              Invocation.method(#copySync, [newPath]),
            ),
          )
          as _i6.File);

  @override
  _i10.Future<int> length() =>
      (super.noSuchMethod(
            Invocation.method(#length, []),
            returnValue: _i10.Future<int>.value(0),
            returnValueForMissingStub: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  int lengthSync() =>
      (super.noSuchMethod(
            Invocation.method(#lengthSync, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i10.Future<DateTime> lastAccessed() =>
      (super.noSuchMethod(
            Invocation.method(#lastAccessed, []),
            returnValue: _i10.Future<DateTime>.value(
              _FakeDateTime_8(this, Invocation.method(#lastAccessed, [])),
            ),
            returnValueForMissingStub: _i10.Future<DateTime>.value(
              _FakeDateTime_8(this, Invocation.method(#lastAccessed, [])),
            ),
          )
          as _i10.Future<DateTime>);

  @override
  DateTime lastAccessedSync() =>
      (super.noSuchMethod(
            Invocation.method(#lastAccessedSync, []),
            returnValue: _FakeDateTime_8(
              this,
              Invocation.method(#lastAccessedSync, []),
            ),
            returnValueForMissingStub: _FakeDateTime_8(
              this,
              Invocation.method(#lastAccessedSync, []),
            ),
          )
          as DateTime);

  @override
  _i10.Future<dynamic> setLastAccessed(DateTime? time) =>
      (super.noSuchMethod(
            Invocation.method(#setLastAccessed, [time]),
            returnValue: _i10.Future<dynamic>.value(),
            returnValueForMissingStub: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  void setLastAccessedSync(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setLastAccessedSync, [time]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<DateTime> lastModified() =>
      (super.noSuchMethod(
            Invocation.method(#lastModified, []),
            returnValue: _i10.Future<DateTime>.value(
              _FakeDateTime_8(this, Invocation.method(#lastModified, [])),
            ),
            returnValueForMissingStub: _i10.Future<DateTime>.value(
              _FakeDateTime_8(this, Invocation.method(#lastModified, [])),
            ),
          )
          as _i10.Future<DateTime>);

  @override
  DateTime lastModifiedSync() =>
      (super.noSuchMethod(
            Invocation.method(#lastModifiedSync, []),
            returnValue: _FakeDateTime_8(
              this,
              Invocation.method(#lastModifiedSync, []),
            ),
            returnValueForMissingStub: _FakeDateTime_8(
              this,
              Invocation.method(#lastModifiedSync, []),
            ),
          )
          as DateTime);

  @override
  _i10.Future<dynamic> setLastModified(DateTime? time) =>
      (super.noSuchMethod(
            Invocation.method(#setLastModified, [time]),
            returnValue: _i10.Future<dynamic>.value(),
            returnValueForMissingStub: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  void setLastModifiedSync(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setLastModifiedSync, [time]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<_i6.RandomAccessFile> open({
    _i6.FileMode? mode = _i6.FileMode.read,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#open, [], {#mode: mode}),
            returnValue: _i10.Future<_i6.RandomAccessFile>.value(
              _FakeRandomAccessFile_9(
                this,
                Invocation.method(#open, [], {#mode: mode}),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i6.RandomAccessFile>.value(
              _FakeRandomAccessFile_9(
                this,
                Invocation.method(#open, [], {#mode: mode}),
              ),
            ),
          )
          as _i10.Future<_i6.RandomAccessFile>);

  @override
  _i6.RandomAccessFile openSync({_i6.FileMode? mode = _i6.FileMode.read}) =>
      (super.noSuchMethod(
            Invocation.method(#openSync, [], {#mode: mode}),
            returnValue: _FakeRandomAccessFile_9(
              this,
              Invocation.method(#openSync, [], {#mode: mode}),
            ),
            returnValueForMissingStub: _FakeRandomAccessFile_9(
              this,
              Invocation.method(#openSync, [], {#mode: mode}),
            ),
          )
          as _i6.RandomAccessFile);

  @override
  _i10.Stream<List<int>> openRead([int? start, int? end]) =>
      (super.noSuchMethod(
            Invocation.method(#openRead, [start, end]),
            returnValue: _i10.Stream<List<int>>.empty(),
            returnValueForMissingStub: _i10.Stream<List<int>>.empty(),
          )
          as _i10.Stream<List<int>>);

  @override
  _i6.IOSink openWrite({
    _i6.FileMode? mode = _i6.FileMode.write,
    _i16.Encoding? encoding = const _i16.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#openWrite, [], {
              #mode: mode,
              #encoding: encoding,
            }),
            returnValue: _FakeIOSink_10(
              this,
              Invocation.method(#openWrite, [], {
                #mode: mode,
                #encoding: encoding,
              }),
            ),
            returnValueForMissingStub: _FakeIOSink_10(
              this,
              Invocation.method(#openWrite, [], {
                #mode: mode,
                #encoding: encoding,
              }),
            ),
          )
          as _i6.IOSink);

  @override
  _i10.Future<_i17.Uint8List> readAsBytes() =>
      (super.noSuchMethod(
            Invocation.method(#readAsBytes, []),
            returnValue: _i10.Future<_i17.Uint8List>.value(_i17.Uint8List(0)),
            returnValueForMissingStub: _i10.Future<_i17.Uint8List>.value(
              _i17.Uint8List(0),
            ),
          )
          as _i10.Future<_i17.Uint8List>);

  @override
  _i17.Uint8List readAsBytesSync() =>
      (super.noSuchMethod(
            Invocation.method(#readAsBytesSync, []),
            returnValue: _i17.Uint8List(0),
            returnValueForMissingStub: _i17.Uint8List(0),
          )
          as _i17.Uint8List);

  @override
  _i10.Future<String> readAsString({
    _i16.Encoding? encoding = const _i16.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsString, [], {#encoding: encoding}),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [], {#encoding: encoding}),
              ),
            ),
            returnValueForMissingStub: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [], {#encoding: encoding}),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  String readAsStringSync({_i16.Encoding? encoding = const _i16.Utf8Codec()}) =>
      (super.noSuchMethod(
            Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
            ),
          )
          as String);

  @override
  _i10.Future<List<String>> readAsLines({
    _i16.Encoding? encoding = const _i16.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsLines, [], {#encoding: encoding}),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i10.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i10.Future<List<String>>);

  @override
  List<String> readAsLinesSync({
    _i16.Encoding? encoding = const _i16.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsLinesSync, [], {#encoding: encoding}),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  _i10.Future<_i6.File> writeAsBytes(
    List<int>? bytes, {
    _i6.FileMode? mode = _i6.FileMode.write,
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeAsBytes,
              [bytes],
              {#mode: mode, #flush: flush},
            ),
            returnValue: _i10.Future<_i6.File>.value(
              _FakeFile_4(
                this,
                Invocation.method(
                  #writeAsBytes,
                  [bytes],
                  {#mode: mode, #flush: flush},
                ),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i6.File>.value(
              _FakeFile_4(
                this,
                Invocation.method(
                  #writeAsBytes,
                  [bytes],
                  {#mode: mode, #flush: flush},
                ),
              ),
            ),
          )
          as _i10.Future<_i6.File>);

  @override
  void writeAsBytesSync(
    List<int>? bytes, {
    _i6.FileMode? mode = _i6.FileMode.write,
    bool? flush = false,
  }) => super.noSuchMethod(
    Invocation.method(#writeAsBytesSync, [bytes], {#mode: mode, #flush: flush}),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<_i6.File> writeAsString(
    String? contents, {
    _i6.FileMode? mode = _i6.FileMode.write,
    _i16.Encoding? encoding = const _i16.Utf8Codec(),
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeAsString,
              [contents],
              {#mode: mode, #encoding: encoding, #flush: flush},
            ),
            returnValue: _i10.Future<_i6.File>.value(
              _FakeFile_4(
                this,
                Invocation.method(
                  #writeAsString,
                  [contents],
                  {#mode: mode, #encoding: encoding, #flush: flush},
                ),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i6.File>.value(
              _FakeFile_4(
                this,
                Invocation.method(
                  #writeAsString,
                  [contents],
                  {#mode: mode, #encoding: encoding, #flush: flush},
                ),
              ),
            ),
          )
          as _i10.Future<_i6.File>);

  @override
  void writeAsStringSync(
    String? contents, {
    _i6.FileMode? mode = _i6.FileMode.write,
    _i16.Encoding? encoding = const _i16.Utf8Codec(),
    bool? flush = false,
  }) => super.noSuchMethod(
    Invocation.method(
      #writeAsStringSync,
      [contents],
      {#mode: mode, #encoding: encoding, #flush: flush},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<bool> exists() =>
      (super.noSuchMethod(
            Invocation.method(#exists, []),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  bool existsSync() =>
      (super.noSuchMethod(
            Invocation.method(#existsSync, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i10.Future<String> resolveSymbolicLinks() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSymbolicLinks, []),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#resolveSymbolicLinks, []),
              ),
            ),
            returnValueForMissingStub: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#resolveSymbolicLinks, []),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  String resolveSymbolicLinksSync() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSymbolicLinksSync, []),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#resolveSymbolicLinksSync, []),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.method(#resolveSymbolicLinksSync, []),
            ),
          )
          as String);

  @override
  _i10.Future<_i6.FileStat> stat() =>
      (super.noSuchMethod(
            Invocation.method(#stat, []),
            returnValue: _i10.Future<_i6.FileStat>.value(
              _FakeFileStat_11(this, Invocation.method(#stat, [])),
            ),
            returnValueForMissingStub: _i10.Future<_i6.FileStat>.value(
              _FakeFileStat_11(this, Invocation.method(#stat, [])),
            ),
          )
          as _i10.Future<_i6.FileStat>);

  @override
  _i6.FileStat statSync() =>
      (super.noSuchMethod(
            Invocation.method(#statSync, []),
            returnValue: _FakeFileStat_11(
              this,
              Invocation.method(#statSync, []),
            ),
            returnValueForMissingStub: _FakeFileStat_11(
              this,
              Invocation.method(#statSync, []),
            ),
          )
          as _i6.FileStat);

  @override
  _i10.Stream<_i6.FileSystemEvent> watch({
    int? events = 15,
    bool? recursive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [], {
              #events: events,
              #recursive: recursive,
            }),
            returnValue: _i10.Stream<_i6.FileSystemEvent>.empty(),
            returnValueForMissingStub: _i10.Stream<_i6.FileSystemEvent>.empty(),
          )
          as _i10.Stream<_i6.FileSystemEvent>);
}

/// A class which mocks [RunningExecutablesRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockRunningExecutablesRepo<SlotType> extends _i1.Mock
    implements _i18.RunningExecutablesRepo<SlotType> {
  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void addRunningProcess({
    required _i8.WinePrefix? prefix,
    required SlotType? slot,
    required _i4.WineProcess? wineProcess,
  }) => super.noSuchMethod(
    Invocation.method(#addRunningProcess, [], {
      #prefix: prefix,
      #slot: slot,
      #wineProcess: wineProcess,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i4.WineProcess? tryFindRunningProcess({
    required _i8.WinePrefix? prefix,
    required SlotType? slot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#tryFindRunningProcess, [], {
              #prefix: prefix,
              #slot: slot,
            }),
            returnValueForMissingStub: null,
          )
          as _i4.WineProcess?);

  @override
  int numProcessesRunningInPrefix(_i8.WinePrefix? prefix) =>
      (super.noSuchMethod(
            Invocation.method(#numProcessesRunningInPrefix, [prefix]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int totalRunningProcesses() =>
      (super.noSuchMethod(
            Invocation.method(#totalRunningProcesses, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  void addListener(_i19.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i19.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WineInstallationDescriptor].
///
/// See the documentation for Mockito's code generation for more information.
class MockWineInstallationDescriptor extends _i1.Mock
    implements _i2.WineInstallationDescriptor {
  @override
  bool get needsHomeIsolation =>
      (super.noSuchMethod(
            Invocation.getter(#needsHomeIsolation),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasBundledWinetricks =>
      (super.noSuchMethod(
            Invocation.getter(#hasBundledWinetricks),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String getInnermostPrefixDir({
    required _i5.WinePrefixDirStructure? prefixDirStructure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getInnermostPrefixDir, [], {
              #prefixDirStructure: prefixDirStructure,
            }),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#getInnermostPrefixDir, [], {
                #prefixDirStructure: prefixDirStructure,
              }),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.method(#getInnermostPrefixDir, [], {
                #prefixDirStructure: prefixDirStructure,
              }),
            ),
          )
          as String);

  @override
  List<String> buildWineInvocationCommand({required List<String>? wineArgs}) =>
      (super.noSuchMethod(
            Invocation.method(#buildWineInvocationCommand, [], {
              #wineArgs: wineArgs,
            }),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  List<String> buildWinetricksInvocationCommand({
    required String? externalWinetricksScriptPath,
    required List<String>? winetricksArgs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#buildWinetricksInvocationCommand, [], {
              #externalWinetricksScriptPath: externalWinetricksScriptPath,
              #winetricksArgs: winetricksArgs,
            }),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  Map<String, String> getEnvVarsForWine({
    required _i5.WinePrefixDirStructure? prefixDirStructure,
    required String? tempDir,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEnvVarsForWine, [], {
              #prefixDirStructure: prefixDirStructure,
              #tempDir: tempDir,
            }),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> getEnvVarsForWinetricks({
    required _i5.WinePrefixDirStructure? prefixDirStructure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEnvVarsForWinetricks, [], {
              #prefixDirStructure: prefixDirStructure,
            }),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);
}

/// A class which mocks [WineProcessRunnerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWineProcessRunnerService extends _i1.Mock
    implements _i4.WineProcessRunnerService {
  @override
  _i10.Future<_i4.WineProcess> start({
    required List<String>? commandLine,
    required Map<String, String>? envVars,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#start, [], {
              #commandLine: commandLine,
              #envVars: envVars,
            }),
            returnValue: _i10.Future<_i4.WineProcess>.value(
              _FakeWineProcess_12(
                this,
                Invocation.method(#start, [], {
                  #commandLine: commandLine,
                  #envVars: envVars,
                }),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i4.WineProcess>.value(
              _FakeWineProcess_12(
                this,
                Invocation.method(#start, [], {
                  #commandLine: commandLine,
                  #envVars: envVars,
                }),
              ),
            ),
          )
          as _i10.Future<_i4.WineProcess>);
}

/// A class which mocks [WineProcess].
///
/// See the documentation for Mockito's code generation for more information.
class MockWineProcess extends _i1.Mock implements _i4.WineProcess {
  @override
  _i10.Future<_i4.WineProcessResult> get result =>
      (super.noSuchMethod(
            Invocation.getter(#result),
            returnValue: _i10.Future<_i4.WineProcessResult>.value(
              _FakeWineProcessResult_13(this, Invocation.getter(#result)),
            ),
            returnValueForMissingStub: _i10.Future<_i4.WineProcessResult>.value(
              _FakeWineProcessResult_13(this, Invocation.getter(#result)),
            ),
          )
          as _i10.Future<_i4.WineProcessResult>);

  @override
  bool kill([_i6.ProcessSignal? signal = _i6.ProcessSignal.sigterm]) =>
      (super.noSuchMethod(
            Invocation.method(#kill, [signal]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}
