// Mocks generated by Mockito 5.4.6 from annotations
// in winebar/test/prefix_creation_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:winebar/models/archive_type.dart' as _i15;
import 'package:winebar/models/settings_json_file.dart' as _i2;
import 'package:winebar/models/suppressable_warning.dart' as _i6;
import 'package:winebar/models/wine_build.dart' as _i14;
import 'package:winebar/models/wine_build_source.dart' as _i10;
import 'package:winebar/models/wine_prefix.dart' as _i8;
import 'package:winebar/models/wine_release.dart' as _i13;
import 'package:winebar/repositories/wine_build_source_repo.dart' as _i9;
import 'package:winebar/services/app_settings_service.dart' as _i5;
import 'package:winebar/services/wine_process_runner_service.dart' as _i4;
import 'package:winebar/utils/local_storage_paths.dart' as _i3;
import 'package:winebar/utils/startup_data.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSettingsJsonFile_0 extends _i1.SmartFake
    implements _i2.SettingsJsonFile {
  _FakeSettingsJsonFile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocalStoragePaths_1 extends _i1.SmartFake
    implements _i3.LocalStoragePaths {
  _FakeLocalStoragePaths_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWineProcessRunnerService_2 extends _i1.SmartFake
    implements _i4.WineProcessRunnerService {
  _FakeWineProcessRunnerService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppSettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppSettingsService extends _i1.Mock
    implements _i5.AppSettingsService {
  @override
  _i2.SettingsJsonFile get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeSettingsJsonFile_0(
              this,
              Invocation.getter(#settings),
            ),
            returnValueForMissingStub: _FakeSettingsJsonFile_0(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i2.SettingsJsonFile);

  @override
  void setWarningSuppressed(
    _i6.SuppressableWarning? warning, {
    required bool? suppressed,
  }) => super.noSuchMethod(
    Invocation.method(
      #setWarningSuppressed,
      [warning],
      {#suppressed: suppressed},
    ),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [StartupData].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartupData extends _i1.Mock implements _i7.StartupData {
  @override
  _i3.LocalStoragePaths get localStoragePaths =>
      (super.noSuchMethod(
            Invocation.getter(#localStoragePaths),
            returnValue: _FakeLocalStoragePaths_1(
              this,
              Invocation.getter(#localStoragePaths),
            ),
            returnValueForMissingStub: _FakeLocalStoragePaths_1(
              this,
              Invocation.getter(#localStoragePaths),
            ),
          )
          as _i3.LocalStoragePaths);

  @override
  List<_i8.WinePrefix> get winePrefixes =>
      (super.noSuchMethod(
            Invocation.getter(#winePrefixes),
            returnValue: <_i8.WinePrefix>[],
            returnValueForMissingStub: <_i8.WinePrefix>[],
          )
          as List<_i8.WinePrefix>);

  @override
  _i4.WineProcessRunnerService get wineProcessRunnerService =>
      (super.noSuchMethod(
            Invocation.getter(#wineProcessRunnerService),
            returnValue: _FakeWineProcessRunnerService_2(
              this,
              Invocation.getter(#wineProcessRunnerService),
            ),
            returnValueForMissingStub: _FakeWineProcessRunnerService_2(
              this,
              Invocation.getter(#wineProcessRunnerService),
            ),
          )
          as _i4.WineProcessRunnerService);

  @override
  bool get isIntelHost =>
      (super.noSuchMethod(
            Invocation.getter(#isIntelHost),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get wineWillRunUnderMuvm =>
      (super.noSuchMethod(
            Invocation.getter(#wineWillRunUnderMuvm),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}

/// A class which mocks [WineBuildSourceRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockWineBuildSourceRepo extends _i1.Mock
    implements _i9.WineBuildSourceRepo {
  @override
  List<_i10.WineBuildSource> get sources =>
      (super.noSuchMethod(
            Invocation.getter(#sources),
            returnValue: <_i10.WineBuildSource>[],
            returnValueForMissingStub: <_i10.WineBuildSource>[],
          )
          as List<_i10.WineBuildSource>);
}

/// A class which mocks [WineBuildSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWineBuildSource extends _i1.Mock implements _i10.WineBuildSource {
  @override
  String get label =>
      (super.noSuchMethod(
            Invocation.getter(#label),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#label),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#label),
            ),
          )
          as String);

  @override
  bool get recommended =>
      (super.noSuchMethod(
            Invocation.getter(#recommended),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get directoryName =>
      (super.noSuchMethod(
            Invocation.getter(#directoryName),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#directoryName),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#directoryName),
            ),
          )
          as String);

  @override
  String get circleAvatarText =>
      (super.noSuchMethod(
            Invocation.getter(#circleAvatarText),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#circleAvatarText),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#circleAvatarText),
            ),
          )
          as String);

  @override
  bool get buildsMaySupportBothWin64AndWow64Modes =>
      (super.noSuchMethod(
            Invocation.getter(#buildsMaySupportBothWin64AndWow64Modes),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i12.Future<List<_i13.WineRelease>> getAvailableReleases({
    bool? refresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableReleases, [], {#refresh: refresh}),
            returnValue: _i12.Future<List<_i13.WineRelease>>.value(
              <_i13.WineRelease>[],
            ),
            returnValueForMissingStub:
                _i12.Future<List<_i13.WineRelease>>.value(<_i13.WineRelease>[]),
          )
          as _i12.Future<List<_i13.WineRelease>>);
}

/// A class which mocks [WineRelease].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockWineRelease extends _i1.Mock implements _i13.WineRelease {
  @override
  String get releaseName =>
      (super.noSuchMethod(
            Invocation.getter(#releaseName),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#releaseName),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#releaseName),
            ),
          )
          as String);

  @override
  List<_i14.WineBuild> get builds =>
      (super.noSuchMethod(
            Invocation.getter(#builds),
            returnValue: <_i14.WineBuild>[],
            returnValueForMissingStub: <_i14.WineBuild>[],
          )
          as List<_i14.WineBuild>);

  @override
  List<Object> get props =>
      (super.noSuchMethod(
            Invocation.getter(#props),
            returnValue: <Object>[],
            returnValueForMissingStub: <Object>[],
          )
          as List<Object>);
}

/// A class which mocks [WineBuild].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockWineBuild extends _i1.Mock implements _i14.WineBuild {
  @override
  String get archiveFileName =>
      (super.noSuchMethod(
            Invocation.getter(#archiveFileName),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#archiveFileName),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#archiveFileName),
            ),
          )
          as String);

  @override
  _i15.ArchiveType get archiveType =>
      (super.noSuchMethod(
            Invocation.getter(#archiveType),
            returnValue: _i15.ArchiveType.tarGz,
            returnValueForMissingStub: _i15.ArchiveType.tarGz,
          )
          as _i15.ArchiveType);

  @override
  String get downloadUrl =>
      (super.noSuchMethod(
            Invocation.getter(#downloadUrl),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#downloadUrl),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#downloadUrl),
            ),
          )
          as String);

  @override
  List<Object> get props =>
      (super.noSuchMethod(
            Invocation.getter(#props),
            returnValue: <Object>[],
            returnValueForMissingStub: <Object>[],
          )
          as List<Object>);

  @override
  bool get hasWow64InName =>
      (super.noSuchMethod(
            Invocation.getter(#hasWow64InName),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}
