// Mocks generated by Mockito 5.4.6 from annotations
// in winebar/test/prefix_settings_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:convert' as _i26;
import 'dart:io' as _i8;
import 'dart:typed_data' as _i27;
import 'dart:ui' as _i28;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i20;
import 'package:winebar/models/dxvk_build.dart' as _i24;
import 'package:winebar/models/settings_json_file.dart' as _i2;
import 'package:winebar/models/special_executable_slot.dart' as _i17;
import 'package:winebar/models/suppressable_warning.dart' as _i11;
import 'package:winebar/models/wine_build.dart' as _i23;
import 'package:winebar/models/wine_build_source.dart' as _i21;
import 'package:winebar/models/wine_locale.dart' as _i25;
import 'package:winebar/models/wine_prefix.dart' as _i15;
import 'package:winebar/models/wine_prefix_dir_structure.dart' as _i9;
import 'package:winebar/models/wine_release.dart' as _i22;
import 'package:winebar/repositories/running_executables_repo.dart' as _i16;
import 'package:winebar/repositories/wine_locale_repo.dart' as _i6;
import 'package:winebar/services/app_settings_service.dart' as _i10;
import 'package:winebar/services/download_and_extraction_service.dart' as _i13;
import 'package:winebar/services/dxvk_installation_service.dart' as _i3;
import 'package:winebar/services/utility_service.dart' as _i19;
import 'package:winebar/services/wine_process_runner_service.dart' as _i7;
import 'package:winebar/utils/local_storage_paths.dart' as _i5;
import 'package:winebar/utils/startup_data.dart' as _i14;
import 'package:winebar/utils/wine_installation_descriptor.dart' as _i4;
import 'package:winebar/utils/wine_tasks.dart' as _i29;

import 'prefix_settings_dialog_test.dart' as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSettingsJsonFile_0 extends _i1.SmartFake
    implements _i2.SettingsJsonFile {
  _FakeSettingsJsonFile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDxvkInstallationPlan_1 extends _i1.SmartFake
    implements _i3.DxvkInstallationPlan {
  _FakeDxvkInstallationPlan_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWineInstallationDescriptor_2 extends _i1.SmartFake
    implements _i4.WineInstallationDescriptor {
  _FakeWineInstallationDescriptor_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocalStoragePaths_3 extends _i1.SmartFake
    implements _i5.LocalStoragePaths {
  _FakeLocalStoragePaths_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWineLocaleRepo_4 extends _i1.SmartFake
    implements _i6.WineLocaleRepo {
  _FakeWineLocaleRepo_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWineProcessRunnerService_5 extends _i1.SmartFake
    implements _i7.WineProcessRunnerService {
  _FakeWineProcessRunnerService_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDirectory_6 extends _i1.SmartFake implements _i8.Directory {
  _FakeDirectory_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWinePrefixDirStructure_7 extends _i1.SmartFake
    implements _i9.WinePrefixDirStructure {
  _FakeWinePrefixDirStructure_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_8 extends _i1.SmartFake implements _i8.File {
  _FakeFile_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_9 extends _i1.SmartFake implements Uri {
  _FakeUri_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileSystemEntity_10 extends _i1.SmartFake
    implements _i8.FileSystemEntity {
  _FakeFileSystemEntity_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_11 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRandomAccessFile_12 extends _i1.SmartFake
    implements _i8.RandomAccessFile {
  _FakeRandomAccessFile_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSink_13 extends _i1.SmartFake implements _i8.IOSink {
  _FakeIOSink_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileStat_14 extends _i1.SmartFake implements _i8.FileStat {
  _FakeFileStat_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppSettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppSettingsService extends _i1.Mock
    implements _i10.AppSettingsService {
  @override
  _i2.SettingsJsonFile get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeSettingsJsonFile_0(
              this,
              Invocation.getter(#settings),
            ),
            returnValueForMissingStub: _FakeSettingsJsonFile_0(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i2.SettingsJsonFile);

  @override
  void setWarningSuppressed(
    _i11.SuppressableWarning? warning, {
    required bool? suppressed,
  }) => super.noSuchMethod(
    Invocation.method(
      #setWarningSuppressed,
      [warning],
      {#suppressed: suppressed},
    ),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DxvkInstallationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDxvkInstallationService extends _i1.Mock
    implements _i3.DxvkInstallationService {
  @override
  _i12.Future<_i3.DxvkInstallationPlan> buildDxvkInstallationPlan({
    required bool? dxvkWanted,
    required _i5.LocalStoragePaths? localStoragePaths,
    required _i4.WineInstallationDescriptor? wineInstDescriptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#buildDxvkInstallationPlan, [], {
              #dxvkWanted: dxvkWanted,
              #localStoragePaths: localStoragePaths,
              #wineInstDescriptor: wineInstDescriptor,
            }),
            returnValue: _i12.Future<_i3.DxvkInstallationPlan>.value(
              _FakeDxvkInstallationPlan_1(
                this,
                Invocation.method(#buildDxvkInstallationPlan, [], {
                  #dxvkWanted: dxvkWanted,
                  #localStoragePaths: localStoragePaths,
                  #wineInstDescriptor: wineInstDescriptor,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i12.Future<_i3.DxvkInstallationPlan>.value(
                  _FakeDxvkInstallationPlan_1(
                    this,
                    Invocation.method(#buildDxvkInstallationPlan, [], {
                      #dxvkWanted: dxvkWanted,
                      #localStoragePaths: localStoragePaths,
                      #wineInstDescriptor: wineInstDescriptor,
                    }),
                  ),
                ),
          )
          as _i12.Future<_i3.DxvkInstallationPlan>);
}

/// A class which mocks [DxvkInstallationPlan].
///
/// See the documentation for Mockito's code generation for more information.
class MockDxvkInstallationPlan extends _i1.Mock
    implements _i3.DxvkInstallationPlan {
  @override
  bool get needDownloadAndExtract =>
      (super.noSuchMethod(
            Invocation.getter(#needDownloadAndExtract),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get needInstall =>
      (super.noSuchMethod(
            Invocation.getter(#needInstall),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get needActivate =>
      (super.noSuchMethod(
            Invocation.getter(#needActivate),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i12.Future<_i13.DownloadAndExtractionOutcome> downloadAndExtract({
    required _i8.Directory? tempExtractionDir,
    void Function(void Function())? cancelHookReceiver,
    _i13.DownloadAndExtractionProgressCallback? progressCallback,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#downloadAndExtract, [], {
              #tempExtractionDir: tempExtractionDir,
              #cancelHookReceiver: cancelHookReceiver,
              #progressCallback: progressCallback,
            }),
            returnValue: _i12.Future<_i13.DownloadAndExtractionOutcome>.value(
              _i13.DownloadAndExtractionOutcome.succeeded,
            ),
            returnValueForMissingStub:
                _i12.Future<_i13.DownloadAndExtractionOutcome>.value(
                  _i13.DownloadAndExtractionOutcome.succeeded,
                ),
          )
          as _i12.Future<_i13.DownloadAndExtractionOutcome>);

  @override
  _i12.Future<void> install({
    required _i9.WinePrefixDirStructure? prefixDirStructure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#install, [], {
              #prefixDirStructure: prefixDirStructure,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> activate({
    void Function(void Function())? cancelHookReceiver,
    required _i14.StartupData? startupData,
    required _i15.WinePrefix? winePrefix,
    required _i16.RunningExecutablesRepo<_i17.SpecialExecutableSlot>?
    runningSpecialExecutablesRepo,
    required _i17.SpecialExecutableSlot? specialExecutableSlot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#activate, [], {
              #cancelHookReceiver: cancelHookReceiver,
              #startupData: startupData,
              #winePrefix: winePrefix,
              #runningSpecialExecutablesRepo: runningSpecialExecutablesRepo,
              #specialExecutableSlot: specialExecutableSlot,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [UpdatedPrefixReceiver].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdatedPrefixReceiver extends _i1.Mock
    implements _i18.UpdatedPrefixReceiver {
  @override
  void handleUpdatedPrefix(_i15.WinePrefix? updatedPrefix) =>
      super.noSuchMethod(
        Invocation.method(#handleUpdatedPrefix, [updatedPrefix]),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UtilityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUtilityService extends _i1.Mock implements _i19.UtilityService {
  @override
  _i12.Future<_i4.WineInstallationDescriptor>
  wineInstallationDescriptorForWineInstallDir(String? wineInstallDir) =>
      (super.noSuchMethod(
            Invocation.method(#wineInstallationDescriptorForWineInstallDir, [
              wineInstallDir,
            ]),
            returnValue: _i12.Future<_i4.WineInstallationDescriptor>.value(
              _FakeWineInstallationDescriptor_2(
                this,
                Invocation.method(
                  #wineInstallationDescriptorForWineInstallDir,
                  [wineInstallDir],
                ),
              ),
            ),
            returnValueForMissingStub:
                _i12.Future<_i4.WineInstallationDescriptor>.value(
                  _FakeWineInstallationDescriptor_2(
                    this,
                    Invocation.method(
                      #wineInstallationDescriptorForWineInstallDir,
                      [wineInstallDir],
                    ),
                  ),
                ),
          )
          as _i12.Future<_i4.WineInstallationDescriptor>);
}

/// A class which mocks [StartupData].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartupData extends _i1.Mock implements _i14.StartupData {
  @override
  _i5.LocalStoragePaths get localStoragePaths =>
      (super.noSuchMethod(
            Invocation.getter(#localStoragePaths),
            returnValue: _FakeLocalStoragePaths_3(
              this,
              Invocation.getter(#localStoragePaths),
            ),
            returnValueForMissingStub: _FakeLocalStoragePaths_3(
              this,
              Invocation.getter(#localStoragePaths),
            ),
          )
          as _i5.LocalStoragePaths);

  @override
  List<_i15.WinePrefix> get winePrefixes =>
      (super.noSuchMethod(
            Invocation.getter(#winePrefixes),
            returnValue: <_i15.WinePrefix>[],
            returnValueForMissingStub: <_i15.WinePrefix>[],
          )
          as List<_i15.WinePrefix>);

  @override
  _i6.WineLocaleRepo get wineLocaleRepo =>
      (super.noSuchMethod(
            Invocation.getter(#wineLocaleRepo),
            returnValue: _FakeWineLocaleRepo_4(
              this,
              Invocation.getter(#wineLocaleRepo),
            ),
            returnValueForMissingStub: _FakeWineLocaleRepo_4(
              this,
              Invocation.getter(#wineLocaleRepo),
            ),
          )
          as _i6.WineLocaleRepo);

  @override
  _i7.WineProcessRunnerService get wineProcessRunnerService =>
      (super.noSuchMethod(
            Invocation.getter(#wineProcessRunnerService),
            returnValue: _FakeWineProcessRunnerService_5(
              this,
              Invocation.getter(#wineProcessRunnerService),
            ),
            returnValueForMissingStub: _FakeWineProcessRunnerService_5(
              this,
              Invocation.getter(#wineProcessRunnerService),
            ),
          )
          as _i7.WineProcessRunnerService);

  @override
  bool get isIntelHost =>
      (super.noSuchMethod(
            Invocation.getter(#isIntelHost),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get wineWillRunUnderMuvm =>
      (super.noSuchMethod(
            Invocation.getter(#wineWillRunUnderMuvm),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}

/// A class which mocks [LocalStoragePaths].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStoragePaths extends _i1.Mock implements _i5.LocalStoragePaths {
  @override
  String get homeDir =>
      (super.noSuchMethod(
            Invocation.getter(#homeDir),
            returnValue: _i20.dummyValue<String>(
              this,
              Invocation.getter(#homeDir),
            ),
            returnValueForMissingStub: _i20.dummyValue<String>(
              this,
              Invocation.getter(#homeDir),
            ),
          )
          as String);

  @override
  String get toplevelDataDir =>
      (super.noSuchMethod(
            Invocation.getter(#toplevelDataDir),
            returnValue: _i20.dummyValue<String>(
              this,
              Invocation.getter(#toplevelDataDir),
            ),
            returnValueForMissingStub: _i20.dummyValue<String>(
              this,
              Invocation.getter(#toplevelDataDir),
            ),
          )
          as String);

  @override
  String get settingsJsonFilePath =>
      (super.noSuchMethod(
            Invocation.getter(#settingsJsonFilePath),
            returnValue: _i20.dummyValue<String>(
              this,
              Invocation.getter(#settingsJsonFilePath),
            ),
            returnValueForMissingStub: _i20.dummyValue<String>(
              this,
              Invocation.getter(#settingsJsonFilePath),
            ),
          )
          as String);

  @override
  String get wineInstallsDir =>
      (super.noSuchMethod(
            Invocation.getter(#wineInstallsDir),
            returnValue: _i20.dummyValue<String>(
              this,
              Invocation.getter(#wineInstallsDir),
            ),
            returnValueForMissingStub: _i20.dummyValue<String>(
              this,
              Invocation.getter(#wineInstallsDir),
            ),
          )
          as String);

  @override
  String get winePrefixesDir =>
      (super.noSuchMethod(
            Invocation.getter(#winePrefixesDir),
            returnValue: _i20.dummyValue<String>(
              this,
              Invocation.getter(#winePrefixesDir),
            ),
            returnValueForMissingStub: _i20.dummyValue<String>(
              this,
              Invocation.getter(#winePrefixesDir),
            ),
          )
          as String);

  @override
  String get dxvkPackagesDir =>
      (super.noSuchMethod(
            Invocation.getter(#dxvkPackagesDir),
            returnValue: _i20.dummyValue<String>(
              this,
              Invocation.getter(#dxvkPackagesDir),
            ),
            returnValueForMissingStub: _i20.dummyValue<String>(
              this,
              Invocation.getter(#dxvkPackagesDir),
            ),
          )
          as String);

  @override
  String get tempDir =>
      (super.noSuchMethod(
            Invocation.getter(#tempDir),
            returnValue: _i20.dummyValue<String>(
              this,
              Invocation.getter(#tempDir),
            ),
            returnValueForMissingStub: _i20.dummyValue<String>(
              this,
              Invocation.getter(#tempDir),
            ),
          )
          as String);

  @override
  _i12.Future<_i8.Directory> createProcessOutputDir() =>
      (super.noSuchMethod(
            Invocation.method(#createProcessOutputDir, []),
            returnValue: _i12.Future<_i8.Directory>.value(
              _FakeDirectory_6(
                this,
                Invocation.method(#createProcessOutputDir, []),
              ),
            ),
            returnValueForMissingStub: _i12.Future<_i8.Directory>.value(
              _FakeDirectory_6(
                this,
                Invocation.method(#createProcessOutputDir, []),
              ),
            ),
          )
          as _i12.Future<_i8.Directory>);

  @override
  String getWineInstallDir({
    required _i21.WineBuildSource? wineBuildSource,
    required _i22.WineRelease? wineRelease,
    required _i23.WineBuild? wineBuild,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWineInstallDir, [], {
              #wineBuildSource: wineBuildSource,
              #wineRelease: wineRelease,
              #wineBuild: wineBuild,
            }),
            returnValue: _i20.dummyValue<String>(
              this,
              Invocation.method(#getWineInstallDir, [], {
                #wineBuildSource: wineBuildSource,
                #wineRelease: wineRelease,
                #wineBuild: wineBuild,
              }),
            ),
            returnValueForMissingStub: _i20.dummyValue<String>(
              this,
              Invocation.method(#getWineInstallDir, [], {
                #wineBuildSource: wineBuildSource,
                #wineRelease: wineRelease,
                #wineBuild: wineBuild,
              }),
            ),
          )
          as String);

  @override
  String getDxvkPackageDir({required _i24.DxvkBuild? dxvkBuild}) =>
      (super.noSuchMethod(
            Invocation.method(#getDxvkPackageDir, [], {#dxvkBuild: dxvkBuild}),
            returnValue: _i20.dummyValue<String>(
              this,
              Invocation.method(#getDxvkPackageDir, [], {
                #dxvkBuild: dxvkBuild,
              }),
            ),
            returnValueForMissingStub: _i20.dummyValue<String>(
              this,
              Invocation.method(#getDxvkPackageDir, [], {
                #dxvkBuild: dxvkBuild,
              }),
            ),
          )
          as String);

  @override
  _i9.WinePrefixDirStructure getWinePrefixDirStructure({
    required String? prefixName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWinePrefixDirStructure, [], {
              #prefixName: prefixName,
            }),
            returnValue: _FakeWinePrefixDirStructure_7(
              this,
              Invocation.method(#getWinePrefixDirStructure, [], {
                #prefixName: prefixName,
              }),
            ),
            returnValueForMissingStub: _FakeWinePrefixDirStructure_7(
              this,
              Invocation.method(#getWinePrefixDirStructure, [], {
                #prefixName: prefixName,
              }),
            ),
          )
          as _i9.WinePrefixDirStructure);
}

/// A class which mocks [WineLocaleRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockWineLocaleRepo extends _i1.Mock implements _i6.WineLocaleRepo {
  @override
  Iterable<_i25.WineLocale> get localesOrderedByDisplayString =>
      (super.noSuchMethod(
            Invocation.getter(#localesOrderedByDisplayString),
            returnValue: <_i25.WineLocale>[],
            returnValueForMissingStub: <_i25.WineLocale>[],
          )
          as Iterable<_i25.WineLocale>);
}

/// A class which mocks [IoOps].
///
/// See the documentation for Mockito's code generation for more information.
class MockIoOps extends _i1.Mock implements _i18.IoOps {
  @override
  _i8.File createFile(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#createFile, [path]),
            returnValue: _FakeFile_8(
              this,
              Invocation.method(#createFile, [path]),
            ),
            returnValueForMissingStub: _FakeFile_8(
              this,
              Invocation.method(#createFile, [path]),
            ),
          )
          as _i8.File);
}

/// A class which mocks [File].
///
/// See the documentation for Mockito's code generation for more information.
class MockFile extends _i1.Mock implements _i8.File {
  @override
  _i8.File get absolute =>
      (super.noSuchMethod(
            Invocation.getter(#absolute),
            returnValue: _FakeFile_8(this, Invocation.getter(#absolute)),
            returnValueForMissingStub: _FakeFile_8(
              this,
              Invocation.getter(#absolute),
            ),
          )
          as _i8.File);

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i20.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
            returnValueForMissingStub: _i20.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
          )
          as String);

  @override
  Uri get uri =>
      (super.noSuchMethod(
            Invocation.getter(#uri),
            returnValue: _FakeUri_9(this, Invocation.getter(#uri)),
            returnValueForMissingStub: _FakeUri_9(
              this,
              Invocation.getter(#uri),
            ),
          )
          as Uri);

  @override
  bool get isAbsolute =>
      (super.noSuchMethod(
            Invocation.getter(#isAbsolute),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Directory get parent =>
      (super.noSuchMethod(
            Invocation.getter(#parent),
            returnValue: _FakeDirectory_6(this, Invocation.getter(#parent)),
            returnValueForMissingStub: _FakeDirectory_6(
              this,
              Invocation.getter(#parent),
            ),
          )
          as _i8.Directory);

  @override
  _i12.Future<_i8.File> create({
    bool? recursive = false,
    bool? exclusive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #recursive: recursive,
              #exclusive: exclusive,
            }),
            returnValue: _i12.Future<_i8.File>.value(
              _FakeFile_8(
                this,
                Invocation.method(#create, [], {
                  #recursive: recursive,
                  #exclusive: exclusive,
                }),
              ),
            ),
            returnValueForMissingStub: _i12.Future<_i8.File>.value(
              _FakeFile_8(
                this,
                Invocation.method(#create, [], {
                  #recursive: recursive,
                  #exclusive: exclusive,
                }),
              ),
            ),
          )
          as _i12.Future<_i8.File>);

  @override
  void createSync({bool? recursive = false, bool? exclusive = false}) =>
      super.noSuchMethod(
        Invocation.method(#createSync, [], {
          #recursive: recursive,
          #exclusive: exclusive,
        }),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<_i8.File> rename(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#rename, [newPath]),
            returnValue: _i12.Future<_i8.File>.value(
              _FakeFile_8(this, Invocation.method(#rename, [newPath])),
            ),
            returnValueForMissingStub: _i12.Future<_i8.File>.value(
              _FakeFile_8(this, Invocation.method(#rename, [newPath])),
            ),
          )
          as _i12.Future<_i8.File>);

  @override
  _i8.File renameSync(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#renameSync, [newPath]),
            returnValue: _FakeFile_8(
              this,
              Invocation.method(#renameSync, [newPath]),
            ),
            returnValueForMissingStub: _FakeFile_8(
              this,
              Invocation.method(#renameSync, [newPath]),
            ),
          )
          as _i8.File);

  @override
  _i12.Future<_i8.FileSystemEntity> delete({bool? recursive = false}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {#recursive: recursive}),
            returnValue: _i12.Future<_i8.FileSystemEntity>.value(
              _FakeFileSystemEntity_10(
                this,
                Invocation.method(#delete, [], {#recursive: recursive}),
              ),
            ),
            returnValueForMissingStub: _i12.Future<_i8.FileSystemEntity>.value(
              _FakeFileSystemEntity_10(
                this,
                Invocation.method(#delete, [], {#recursive: recursive}),
              ),
            ),
          )
          as _i12.Future<_i8.FileSystemEntity>);

  @override
  void deleteSync({bool? recursive = false}) => super.noSuchMethod(
    Invocation.method(#deleteSync, [], {#recursive: recursive}),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<_i8.File> copy(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#copy, [newPath]),
            returnValue: _i12.Future<_i8.File>.value(
              _FakeFile_8(this, Invocation.method(#copy, [newPath])),
            ),
            returnValueForMissingStub: _i12.Future<_i8.File>.value(
              _FakeFile_8(this, Invocation.method(#copy, [newPath])),
            ),
          )
          as _i12.Future<_i8.File>);

  @override
  _i8.File copySync(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#copySync, [newPath]),
            returnValue: _FakeFile_8(
              this,
              Invocation.method(#copySync, [newPath]),
            ),
            returnValueForMissingStub: _FakeFile_8(
              this,
              Invocation.method(#copySync, [newPath]),
            ),
          )
          as _i8.File);

  @override
  _i12.Future<int> length() =>
      (super.noSuchMethod(
            Invocation.method(#length, []),
            returnValue: _i12.Future<int>.value(0),
            returnValueForMissingStub: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  int lengthSync() =>
      (super.noSuchMethod(
            Invocation.method(#lengthSync, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i12.Future<DateTime> lastAccessed() =>
      (super.noSuchMethod(
            Invocation.method(#lastAccessed, []),
            returnValue: _i12.Future<DateTime>.value(
              _FakeDateTime_11(this, Invocation.method(#lastAccessed, [])),
            ),
            returnValueForMissingStub: _i12.Future<DateTime>.value(
              _FakeDateTime_11(this, Invocation.method(#lastAccessed, [])),
            ),
          )
          as _i12.Future<DateTime>);

  @override
  DateTime lastAccessedSync() =>
      (super.noSuchMethod(
            Invocation.method(#lastAccessedSync, []),
            returnValue: _FakeDateTime_11(
              this,
              Invocation.method(#lastAccessedSync, []),
            ),
            returnValueForMissingStub: _FakeDateTime_11(
              this,
              Invocation.method(#lastAccessedSync, []),
            ),
          )
          as DateTime);

  @override
  _i12.Future<dynamic> setLastAccessed(DateTime? time) =>
      (super.noSuchMethod(
            Invocation.method(#setLastAccessed, [time]),
            returnValue: _i12.Future<dynamic>.value(),
            returnValueForMissingStub: _i12.Future<dynamic>.value(),
          )
          as _i12.Future<dynamic>);

  @override
  void setLastAccessedSync(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setLastAccessedSync, [time]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<DateTime> lastModified() =>
      (super.noSuchMethod(
            Invocation.method(#lastModified, []),
            returnValue: _i12.Future<DateTime>.value(
              _FakeDateTime_11(this, Invocation.method(#lastModified, [])),
            ),
            returnValueForMissingStub: _i12.Future<DateTime>.value(
              _FakeDateTime_11(this, Invocation.method(#lastModified, [])),
            ),
          )
          as _i12.Future<DateTime>);

  @override
  DateTime lastModifiedSync() =>
      (super.noSuchMethod(
            Invocation.method(#lastModifiedSync, []),
            returnValue: _FakeDateTime_11(
              this,
              Invocation.method(#lastModifiedSync, []),
            ),
            returnValueForMissingStub: _FakeDateTime_11(
              this,
              Invocation.method(#lastModifiedSync, []),
            ),
          )
          as DateTime);

  @override
  _i12.Future<dynamic> setLastModified(DateTime? time) =>
      (super.noSuchMethod(
            Invocation.method(#setLastModified, [time]),
            returnValue: _i12.Future<dynamic>.value(),
            returnValueForMissingStub: _i12.Future<dynamic>.value(),
          )
          as _i12.Future<dynamic>);

  @override
  void setLastModifiedSync(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setLastModifiedSync, [time]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<_i8.RandomAccessFile> open({
    _i8.FileMode? mode = _i8.FileMode.read,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#open, [], {#mode: mode}),
            returnValue: _i12.Future<_i8.RandomAccessFile>.value(
              _FakeRandomAccessFile_12(
                this,
                Invocation.method(#open, [], {#mode: mode}),
              ),
            ),
            returnValueForMissingStub: _i12.Future<_i8.RandomAccessFile>.value(
              _FakeRandomAccessFile_12(
                this,
                Invocation.method(#open, [], {#mode: mode}),
              ),
            ),
          )
          as _i12.Future<_i8.RandomAccessFile>);

  @override
  _i8.RandomAccessFile openSync({_i8.FileMode? mode = _i8.FileMode.read}) =>
      (super.noSuchMethod(
            Invocation.method(#openSync, [], {#mode: mode}),
            returnValue: _FakeRandomAccessFile_12(
              this,
              Invocation.method(#openSync, [], {#mode: mode}),
            ),
            returnValueForMissingStub: _FakeRandomAccessFile_12(
              this,
              Invocation.method(#openSync, [], {#mode: mode}),
            ),
          )
          as _i8.RandomAccessFile);

  @override
  _i12.Stream<List<int>> openRead([int? start, int? end]) =>
      (super.noSuchMethod(
            Invocation.method(#openRead, [start, end]),
            returnValue: _i12.Stream<List<int>>.empty(),
            returnValueForMissingStub: _i12.Stream<List<int>>.empty(),
          )
          as _i12.Stream<List<int>>);

  @override
  _i8.IOSink openWrite({
    _i8.FileMode? mode = _i8.FileMode.write,
    _i26.Encoding? encoding = const _i26.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#openWrite, [], {
              #mode: mode,
              #encoding: encoding,
            }),
            returnValue: _FakeIOSink_13(
              this,
              Invocation.method(#openWrite, [], {
                #mode: mode,
                #encoding: encoding,
              }),
            ),
            returnValueForMissingStub: _FakeIOSink_13(
              this,
              Invocation.method(#openWrite, [], {
                #mode: mode,
                #encoding: encoding,
              }),
            ),
          )
          as _i8.IOSink);

  @override
  _i12.Future<_i27.Uint8List> readAsBytes() =>
      (super.noSuchMethod(
            Invocation.method(#readAsBytes, []),
            returnValue: _i12.Future<_i27.Uint8List>.value(_i27.Uint8List(0)),
            returnValueForMissingStub: _i12.Future<_i27.Uint8List>.value(
              _i27.Uint8List(0),
            ),
          )
          as _i12.Future<_i27.Uint8List>);

  @override
  _i27.Uint8List readAsBytesSync() =>
      (super.noSuchMethod(
            Invocation.method(#readAsBytesSync, []),
            returnValue: _i27.Uint8List(0),
            returnValueForMissingStub: _i27.Uint8List(0),
          )
          as _i27.Uint8List);

  @override
  _i12.Future<String> readAsString({
    _i26.Encoding? encoding = const _i26.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsString, [], {#encoding: encoding}),
            returnValue: _i12.Future<String>.value(
              _i20.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [], {#encoding: encoding}),
              ),
            ),
            returnValueForMissingStub: _i12.Future<String>.value(
              _i20.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [], {#encoding: encoding}),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  String readAsStringSync({_i26.Encoding? encoding = const _i26.Utf8Codec()}) =>
      (super.noSuchMethod(
            Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
            returnValue: _i20.dummyValue<String>(
              this,
              Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
            ),
            returnValueForMissingStub: _i20.dummyValue<String>(
              this,
              Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
            ),
          )
          as String);

  @override
  _i12.Future<List<String>> readAsLines({
    _i26.Encoding? encoding = const _i26.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsLines, [], {#encoding: encoding}),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  List<String> readAsLinesSync({
    _i26.Encoding? encoding = const _i26.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsLinesSync, [], {#encoding: encoding}),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  _i12.Future<_i8.File> writeAsBytes(
    List<int>? bytes, {
    _i8.FileMode? mode = _i8.FileMode.write,
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeAsBytes,
              [bytes],
              {#mode: mode, #flush: flush},
            ),
            returnValue: _i12.Future<_i8.File>.value(
              _FakeFile_8(
                this,
                Invocation.method(
                  #writeAsBytes,
                  [bytes],
                  {#mode: mode, #flush: flush},
                ),
              ),
            ),
            returnValueForMissingStub: _i12.Future<_i8.File>.value(
              _FakeFile_8(
                this,
                Invocation.method(
                  #writeAsBytes,
                  [bytes],
                  {#mode: mode, #flush: flush},
                ),
              ),
            ),
          )
          as _i12.Future<_i8.File>);

  @override
  void writeAsBytesSync(
    List<int>? bytes, {
    _i8.FileMode? mode = _i8.FileMode.write,
    bool? flush = false,
  }) => super.noSuchMethod(
    Invocation.method(#writeAsBytesSync, [bytes], {#mode: mode, #flush: flush}),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<_i8.File> writeAsString(
    String? contents, {
    _i8.FileMode? mode = _i8.FileMode.write,
    _i26.Encoding? encoding = const _i26.Utf8Codec(),
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeAsString,
              [contents],
              {#mode: mode, #encoding: encoding, #flush: flush},
            ),
            returnValue: _i12.Future<_i8.File>.value(
              _FakeFile_8(
                this,
                Invocation.method(
                  #writeAsString,
                  [contents],
                  {#mode: mode, #encoding: encoding, #flush: flush},
                ),
              ),
            ),
            returnValueForMissingStub: _i12.Future<_i8.File>.value(
              _FakeFile_8(
                this,
                Invocation.method(
                  #writeAsString,
                  [contents],
                  {#mode: mode, #encoding: encoding, #flush: flush},
                ),
              ),
            ),
          )
          as _i12.Future<_i8.File>);

  @override
  void writeAsStringSync(
    String? contents, {
    _i8.FileMode? mode = _i8.FileMode.write,
    _i26.Encoding? encoding = const _i26.Utf8Codec(),
    bool? flush = false,
  }) => super.noSuchMethod(
    Invocation.method(
      #writeAsStringSync,
      [contents],
      {#mode: mode, #encoding: encoding, #flush: flush},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<bool> exists() =>
      (super.noSuchMethod(
            Invocation.method(#exists, []),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  bool existsSync() =>
      (super.noSuchMethod(
            Invocation.method(#existsSync, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i12.Future<String> resolveSymbolicLinks() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSymbolicLinks, []),
            returnValue: _i12.Future<String>.value(
              _i20.dummyValue<String>(
                this,
                Invocation.method(#resolveSymbolicLinks, []),
              ),
            ),
            returnValueForMissingStub: _i12.Future<String>.value(
              _i20.dummyValue<String>(
                this,
                Invocation.method(#resolveSymbolicLinks, []),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  String resolveSymbolicLinksSync() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSymbolicLinksSync, []),
            returnValue: _i20.dummyValue<String>(
              this,
              Invocation.method(#resolveSymbolicLinksSync, []),
            ),
            returnValueForMissingStub: _i20.dummyValue<String>(
              this,
              Invocation.method(#resolveSymbolicLinksSync, []),
            ),
          )
          as String);

  @override
  _i12.Future<_i8.FileStat> stat() =>
      (super.noSuchMethod(
            Invocation.method(#stat, []),
            returnValue: _i12.Future<_i8.FileStat>.value(
              _FakeFileStat_14(this, Invocation.method(#stat, [])),
            ),
            returnValueForMissingStub: _i12.Future<_i8.FileStat>.value(
              _FakeFileStat_14(this, Invocation.method(#stat, [])),
            ),
          )
          as _i12.Future<_i8.FileStat>);

  @override
  _i8.FileStat statSync() =>
      (super.noSuchMethod(
            Invocation.method(#statSync, []),
            returnValue: _FakeFileStat_14(
              this,
              Invocation.method(#statSync, []),
            ),
            returnValueForMissingStub: _FakeFileStat_14(
              this,
              Invocation.method(#statSync, []),
            ),
          )
          as _i8.FileStat);

  @override
  _i12.Stream<_i8.FileSystemEvent> watch({
    int? events = 15,
    bool? recursive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [], {
              #events: events,
              #recursive: recursive,
            }),
            returnValue: _i12.Stream<_i8.FileSystemEvent>.empty(),
            returnValueForMissingStub: _i12.Stream<_i8.FileSystemEvent>.empty(),
          )
          as _i12.Stream<_i8.FileSystemEvent>);
}

/// A class which mocks [RunningExecutablesRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockRunningExecutablesRepo<SlotType> extends _i1.Mock
    implements _i16.RunningExecutablesRepo<SlotType> {
  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void addRunningProcess({
    required int? prefixId,
    required SlotType? slot,
    required _i7.WineProcess? wineProcess,
  }) => super.noSuchMethod(
    Invocation.method(#addRunningProcess, [], {
      #prefixId: prefixId,
      #slot: slot,
      #wineProcess: wineProcess,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i7.WineProcess? tryFindRunningProcess({
    required int? prefixId,
    required SlotType? slot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#tryFindRunningProcess, [], {
              #prefixId: prefixId,
              #slot: slot,
            }),
            returnValueForMissingStub: null,
          )
          as _i7.WineProcess?);

  @override
  int numProcessesRunningInPrefix(int? prefixId) =>
      (super.noSuchMethod(
            Invocation.method(#numProcessesRunningInPrefix, [prefixId]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int totalRunningProcesses() =>
      (super.noSuchMethod(
            Invocation.method(#totalRunningProcesses, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  void addListener(_i28.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i28.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WineTasks].
///
/// See the documentation for Mockito's code generation for more information.
class MockWineTasks extends _i1.Mock implements _i29.WineTasks {
  @override
  _i12.Future<void> initializeWinePrefix({
    void Function(void Function())? cancelHookReceiver,
    required _i15.WinePrefix? winePrefix,
    required _i4.WineInstallationDescriptor? wineInstDescriptor,
    required _i16.RunningExecutablesRepo<_i17.SpecialExecutableSlot>?
    runningSpecialExecutablesRepo,
    required _i17.SpecialExecutableSlot? specialExecutableSlot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initializeWinePrefix, [], {
              #cancelHookReceiver: cancelHookReceiver,
              #winePrefix: winePrefix,
              #wineInstDescriptor: wineInstDescriptor,
              #runningSpecialExecutablesRepo: runningSpecialExecutablesRepo,
              #specialExecutableSlot: specialExecutableSlot,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setHiDpiScale({
    required double? hiDpiScale,
    void Function(void Function())? cancelHookReceiver,
    required _i15.WinePrefix? winePrefix,
    required _i4.WineInstallationDescriptor? wineInstDescriptor,
    required _i16.RunningExecutablesRepo<_i17.SpecialExecutableSlot>?
    runningSpecialExecutablesRepo,
    required _i17.SpecialExecutableSlot? specialExecutableSlot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setHiDpiScale, [], {
              #hiDpiScale: hiDpiScale,
              #cancelHookReceiver: cancelHookReceiver,
              #winePrefix: winePrefix,
              #wineInstDescriptor: wineInstDescriptor,
              #runningSpecialExecutablesRepo: runningSpecialExecutablesRepo,
              #specialExecutableSlot: specialExecutableSlot,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setupDxvkDllOverrides({
    void Function(void Function())? cancelHookReceiver,
    required _i14.StartupData? startupData,
    required _i15.WinePrefix? winePrefix,
    required _i4.WineInstallationDescriptor? wineInstDescriptor,
    required _i16.RunningExecutablesRepo<_i17.SpecialExecutableSlot>?
    runningSpecialExecutablesRepo,
    required _i17.SpecialExecutableSlot? specialExecutableSlot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setupDxvkDllOverrides, [], {
              #cancelHookReceiver: cancelHookReceiver,
              #startupData: startupData,
              #winePrefix: winePrefix,
              #wineInstDescriptor: wineInstDescriptor,
              #runningSpecialExecutablesRepo: runningSpecialExecutablesRepo,
              #specialExecutableSlot: specialExecutableSlot,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> clearDxvkDllOverrides({
    void Function(void Function())? cancelHookReceiver,
    required _i14.StartupData? startupData,
    required _i15.WinePrefix? winePrefix,
    required _i4.WineInstallationDescriptor? wineInstDescriptor,
    required _i16.RunningExecutablesRepo<_i17.SpecialExecutableSlot>?
    runningSpecialExecutablesRepo,
    required _i17.SpecialExecutableSlot? specialExecutableSlot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clearDxvkDllOverrides, [], {
              #cancelHookReceiver: cancelHookReceiver,
              #startupData: startupData,
              #winePrefix: winePrefix,
              #wineInstDescriptor: wineInstDescriptor,
              #runningSpecialExecutablesRepo: runningSpecialExecutablesRepo,
              #specialExecutableSlot: specialExecutableSlot,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateDllOverrides({
    required Map<String, String?>? valuesToSetOrRemove,
    void Function(void Function())? cancelHookReceiver,
    required _i14.StartupData? startupData,
    required _i15.WinePrefix? winePrefix,
    required _i4.WineInstallationDescriptor? wineInstDescriptor,
    required _i16.RunningExecutablesRepo<_i17.SpecialExecutableSlot>?
    runningSpecialExecutablesRepo,
    required _i17.SpecialExecutableSlot? specialExecutableSlot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDllOverrides, [], {
              #valuesToSetOrRemove: valuesToSetOrRemove,
              #cancelHookReceiver: cancelHookReceiver,
              #startupData: startupData,
              #winePrefix: winePrefix,
              #wineInstDescriptor: wineInstDescriptor,
              #runningSpecialExecutablesRepo: runningSpecialExecutablesRepo,
              #specialExecutableSlot: specialExecutableSlot,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}
