name: Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: Version name (x.y.z)
      arch:
        required: true
        type: string
        description: Architecture (x64|arm)
      runs-on:
        required: true
        type: string
        description: Github runner name

  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Version name (x.y.z)
      arch:
        required: true
        type: choice
        description: Architecture
        options: 
          - x64
          - arm64
      runs-on:
        required: true
        type: choice
        description: Github runner name
        options:
          - ubuntu-24.04
          - ubuntu-24.04-arm

jobs:
  build-x64:
    name: Build
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 40

    steps:
      - name: Install and configure snapcraft
        run: |
          sudo snap install snapcraft --classic
          sudo snap set snapcraft provider=lxd
      
      - name: Install and configure LXD
        run: |
          sudo snap install lxd
          sudo lxd init --auto

          # From here: https://documentation.ubuntu.com/lxd/latest/howto/network_bridge_firewalld/#prevent-connectivity-issues-with-lxd-and-docker
          sudo iptables -I DOCKER-USER -i lxdbr0 -j ACCEPT
          sudo ip6tables -I DOCKER-USER -i lxdbr0 -j ACCEPT
          sudo iptables  -I DOCKER-USER -o lxdbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
          sudo ip6tables -I DOCKER-USER -o lxdbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

      - name: Check out the winebar-flutter-snap repo
        uses: actions/checkout@v5
        with:
          repository: Tulon/winebar-flutter-snap
          ref: winebar
      
      - name: Build the winebar-flutter snap
        run: |
          sudo usermod -a -G lxd $USER

          # newgrp doesn't work in Github Actions, though sg does.
          sg lxd -c "snapcraft pack -o winebar-flutter.snap"

      # This one is usefull for debugging
      #- name: Upload the built winebar-flutter snap
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: "winebar-flutter-${{ inputs.arch }}.snap"
      #    path: "winebar-flutter.snap"
      #    if-no-files-found: error

      - name: Instal the winebar-flutter snap
        run: |
          sudo snap install winebar-flutter.snap --classic --dangerous
          sudo snap alias winebar-flutter.dart dart
          sudo snap alias winebar-flutter.flutter flutter

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install mingw-w64-i686-dev g++-mingw-w64-i686 binutils-mingw-w64-i686 \
            ninja-build desktop-file-utils

      # This is necessary to be able to run the tools we use for code generation
      - name: Add $HOME/.pub-cache/bin to PATH
        run: |
          echo "PATH=$PATH:$HOME/.pub-cache/bin" >> $GITHUB_ENV

      - name: Clone repository
        uses: actions/checkout@v5

      - name: Regenerate generated files
        run: |
          flutter pub get
          dart pub global activate rps
          dart pub global activate dbus
          rps generate

      - name: Verify the generated files were up to date
        run: |
          # Note that pubspec.lock is ignored because "flutter pub get" may modify
          # it when Dart SDK is upgraded.
          NUM_MODIFIED_FILES=$(git status --porcelain | grep -v pubspec.lock | wc -l)
          if [ "$NUM_MODIFIED_FILES" != "0" ]; then
            echo "The working tree is not clean. The following files were modified:"
            git status --porcelain | grep -v pubspec.lock
            exit 1
          fi

      - name: Build AppImage
        id: build-appimage
        run: |
          ./packaging/scripts/build_appimage.sh ${{ inputs.arch }} ${{ inputs.version }}

      - name: Run ninja manually on a failed build to get better diagnostics 
        if: failure() && steps.build-appimage.outcome == 'failure'
        working-directory: ./build/linux/${{ inputs.arch }}/release
        run: ninja

      - name: Run Native Code Tests
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        working-directory: ./build/linux/${{ inputs.arch }}/release
        run: | 
          cmake --build . --target run_tests

      - name: Run Flutter Tests
        run: flutter test

      - name: Upload build artefacts
        uses: actions/upload-artifact@v4
        with:
          name: "WineBar-${{ inputs.version }}-${{ inputs.arch }}.AppImage"
          path: "build/linux/${{ inputs.arch }}/release/WineBar-${{ inputs.version }}-${{ inputs.arch }}.AppImage"
          if-no-files-found: error
